akvo/akvo-flow-mobile

- app/src/main/java/org/akvo/flow/domain/Dependency.java
* Split the value, not the answer
> [#239] Fix dependency check

- app/src/main/java/org/akvo/flow/ui/fragment/SurveyedLocaleListFragment.java
* Don't hard-code GPS necessity for this Fragment
> [#262] Check for provider availability

- app/src/main/java/org/akvo/flow/activity/SurveyActivity.java
* Remove leading hyphens in the compound name
> [#273] Trim datapoint name

- app/src/main/java/org/akvo/flow/api/parser/xml/SurveyHandler.java
- app/src/main/java/org/akvo/flow/domain/Survey.java
- app/src/main/java/org/akvo/flow/service/BootstrapService.java
- app/src/main/java/org/akvo/flow/util/StatusUtil.java
- app/src/main/res/values-es/strings.xml
- app/src/main/res/values-fr/strings.xml
- app/src/main/res/values/strings.xml
* Parse application id from serverBase property
* Attempt to read form's application
* Abort process if the form belongs to a different instance
* Update (english) strings
> [#242] Check app id in bootstrap process

- app/src/main/java/org/akvo/flow/ui/view/OptionQuestionView.java
* Check flag before accessing 'other' view
> [#287] Check 'other' response allowance

- app/src/main/AndroidManifest.xml
- app/src/main/java/org/akvo/flow/ui/view/QuestionGroupTab.java
* Use 'adjustResize' keyboard mode
* Remove focus claims from ScrollView (question group tab)
> [#285] Avoid claiming focus on scroll changes

- app/src/main/java/org/akvo/flow/service/DataSyncService.java
- app/src/main/java/org/akvo/flow/service/LocationService.java
- app/src/main/java/org/akvo/flow/service/SurveyDownloadService.java
- app/src/main/java/org/akvo/flow/service/TimeCheckService.java
* Only unexpected/important network issues will be reported
> [#290] Do not report IOExceptions

- app/src/main/java/org/akvo/flow/activity/SurveyActivity.java
- app/src/main/java/org/akvo/flow/util/ConstantUtil.java
* FormID, DatapointID, Language
> [#320] Add extra data

- app/src/main/java/org/akvo/flow/dao/SurveyDbAdapter.java
- app/src/main/java/org/akvo/flow/ui/fragment/DrawerFragment.java
* Add context menu option to delete surveys
> [#378] Delete surveys

- app/src/main/java/org/akvo/flow/ui/view/OptionQuestionView.java
* Null responses if no item is checked
> [#411] Do not store empty responses

- app/src/main/java/org/akvo/flow/activity/AddUserActivity.java
- app/src/main/res/layout/add_user_activity.xml
* Force device ID setup upon first run
> [#395] Add device id input

- util/upload-apk/script/flow-releases.sh
Skip instances not ready for deployment
> [#72] Ensure instance contains credentials

- app/src/main/res/values/arrays.xml
Update from "np" to "ne" here, too
> [#330]Use correct lang code in selection array.

- .gitignore
- app/build.gradle
These small changes allow running and debugging the app from Android studio and installing it on a connected device or emulator without having to run the installation script.
Test plan:
There is not nothing to test here just make sure the app builds correctly using the script as well.
> Debug setup for android studio (connect #491)

- app/src/main/AndroidManifest.xml
- app/src/main/java/org/akvo/flow/activity/SettingsActivity.java
- app/src/main/java/org/akvo/flow/api/service/ApkApiService.java
- app/src/main/java/org/akvo/flow/domain/apkupdate/ApkData.java
- app/src/main/java/org/akvo/flow/domain/apkupdate/ApkUpdateMapper.java
- app/src/main/java/org/akvo/flow/service/ApkUpdateHelper.java
- app/src/main/java/org/akvo/flow/service/ApkUpdateService.java
- app/src/main/java/org/akvo/flow/service/BootstrapService.java
- app/src/main/java/org/akvo/flow/service/ServiceToastRunnable.java
- app/src/main/java/org/akvo/flow/service/UserRequestedApkUpdateService.java
- app/src/main/java/org/akvo/flow/ui/Navigator.java
- app/src/main/java/org/akvo/flow/util/PlatformUtil.java
- app/src/main/java/org/akvo/flow/util/StringUtil.java
- app/src/main/java/org/akvo/flow/util/ViewUtil.java
- app/src/main/res/values/strings.xml
User cannot decide when to update the app, he has to wait until the update dialog pops up. It would be nicer to allow him to update when he wants.
Added new entry in settings screen.
Created a new Service based on ApkUpdateService.
Using the same flow as with automatic updates.
Remember to connect the issue
> Update app settings screen (connect #500)

- app/build.gradle
- app/src/main/java/org/akvo/flow/activity/PreferencesActivity.java
- app/src/main/java/org/akvo/flow/util/StringUtil.java
- app/src/test/java/org/akvo/flow/util/StringUtilTest.java
There was no simple way to run tests nor add them.
Created entry for tests and added some basic tests for the class StringUtil
NA
> Added test support (connect #305)

- app/src/main/res/values/strings.xml
Jana asked to update the strings.
Replaced strings
"There was an error when trying to update the app, you are not connected to the internet" to "There was an error when updating the app. You are not connected to the internet."
"There was an error when trying to update the app, please try again" to "There was an error when updating the app. Please try again."
"You already have the latest version of the app". to "You are running the latest version of the app."
NA
> Updated strings after jana's tests (connect #500)

- app/src/main/res/values-es/strings.xml
- app/src/main/res/values-fr/strings.xml
- app/src/main/res/values-pt/strings.xml
Missing latests strings
Have translated and pulled latest strings for spanish, french and portuguese
NA
> Pulled latest translations (connect #524)

- app/src/main/java/org/akvo/flow/activity/SettingsActivity.java
- app/src/main/res/values/strings.xml
The about akvo dialog showed and outdated date
Date will be updated dynamically according to today's year
NA
> About akvo date (connect #545)

- app/build.gradle
There is no lint configuration so running lint on CI will stop as soon as some errors are found
Add basic configuration which can later be extended if needed
NA
> Basic lint config (connect #532)

- app/src/main/java/org/akvo/flow/activity/SettingsActivity.java
Data was updated dynamically
Put date in a constant for now
NA
> Made date into constant (connect #545)

- app/src/main/res/values/strings.xml
Akvo FLOW has to be replaced by Akvo Flow
Replaced the string for english
NA
> Replaced FLOW by Flow (connect #564)

- app/src/main/java/org/akvo/flow/service/SurveyedDataPointSyncService.java
- app/src/main/res/values/strings.xml
The message was cut off in old devices
Make the string shorter
NA
> Fixed long notification message (connect #560) 

- app/src/main/java/org/akvo/flow/activity/SurveyActivity.java
- app/src/main/java/org/akvo/flow/app/FlowApp.java
- app/src/main/java/org/akvo/flow/domain/apkupdate/ApkUpdateStore.java
- app/src/main/java/org/akvo/flow/service/ApkUpdateService.java
- app/src/main/java/org/akvo/flow/util/ConstantUtil.java
- app/src/main/java/org/akvo/flow/util/PlatformUtil.java
- app/src/main/java/org/akvo/flow/util/Prefs.java
- app/src/test/java/org/akvo/flow/domain/apkupdate/ApkUpdateStoreTest.java
The app update "dialog" was displayed every 24h if there was a new version.
The first time the update promt will appear within 24h but after that it will only show after 7 days.
Added tests to the logic.
Prefs are no longer static (was necessary to add tests).
NA
> Improve the app update logic (connect #578)

- app/src/main/res/values-es/strings.xml
- app/src/main/res/values-fr/strings.xml
- app/src/main/res/values-hi/strings.xml
- app/src/main/res/values-in/strings.xml
- app/src/main/res/values-km/strings.xml
- app/src/main/res/values-ne/strings.xml
- app/src/main/res/values-pt/strings.xml
- app/src/main/res/values-vi/strings.xml
- app/src/main/res/values/donottranslate.xml
- app/src/main/res/values/strings.xml
Some translations missing
Did some translations and pulled the ones available
NA
> Pull translations (connect #589)

- .gitignore
- util/scripts/release_notes.py
Release notes had to be generated manually copy-pasting issues and their url
You can pre-generate a list of issues with the script and then add the description by hand
NA
> Added release notes script (connect #604)

- app/src/main/java/org/akvo/flow/serialization/form/SurveyMetaParser.java
- app/src/main/java/org/akvo/flow/service/DataSyncService.java
- app/src/main/java/org/akvo/flow/service/SurveyDownloadService.java
- app/src/main/java/org/akvo/flow/service/SurveyedDataPointSyncService.java
- app/src/main/java/org/akvo/flow/util/logging/SentryTree.java
- app/src/test/java/org/akvo/flow/util/logging/SentryTreeTest.java
Too many exceptions which were not so useful are sent to sentry
Filter out some of the exceptions
Add test
Improve the information sent by some of the exceptions
NA
> Remove useless exceptions (connect #633)

- app/build.gradle
- app/src/androidTest/java/org/akvo/flow/activity/FreeTextSurveyTest.java
- app/src/androidTest/java/org/akvo/flow/testhelper/SurveyInstaller.java
- app/src/androidTest/res/raw/freetextsurvey.xml
Automated UI tests using Espresso framework to ensure basic functionality
Test an instance of free text survey and make sure it's possible to install it and properly edit it
> Automated tests (part 1) (connect #613)

- app/src/main/java/org/akvo/flow/service/DataSyncService.java
Cast inside catch clause 
added catch clause for HttpException
NA
> Added catch clause with HttpException (connect #633)

- app/src/main/java/org/akvo/flow/ui/view/DateQuestionView.java
When the date was in another timezone that gmt, the time displayed to the user was wrong, this was only noticeble when there was a day actual date diference between gmt and the user's date.
Time displayed to user correctly and formatted correctly to gmt timezone before sending to backend
NA
> Fixed wrong date formatting used after date picked (connect #662)

- app/src/main/java/org/akvo/flow/ui/view/GeoQuestionView.java
- app/src/main/res/layout/geo_question_view.xml
- app/src/main/res/values/strings.xml
The "searching" text is being shown once we press the "check geo location" button. This textview is confusing.
Remove the textview, will be replaced by something else in https://github.com/akvo/akvo-flow-mobile/issues/673
> Removed the "searching" textView (connect #674)

- app/build.gradle
- app/src/main/java/org/akvo/flow/activity/GeoshapeActivity.java
- app/src/main/java/org/akvo/flow/event/TimedLocationListener.java
- app/src/main/java/org/akvo/flow/ui/view/GeoQuestionView.java
- app/src/main/res/layout/geo_question_view.xml
- app/src/main/res/values/strings.xml
Timout was not clearly notified to user
Added snackbar to show the use there was a location timeout and she can press retry for another attempt
> Geolocation timeout: add snackbar to notify user (connect #675)

- app/src/main/java/org/akvo/flow/ui/view/GeoInputContainer.java
- app/src/main/java/org/akvo/flow/ui/view/GeoQuestionView.java
- app/src/main/res/layout/geo_manual_info_layout.xml
- app/src/main/res/layout/geo_question_view.xml
- app/src/main/res/values/strings.xml
It was confusing if we started to get geolocation and then typing values manually at the same time the manual values could get overriden
The accuracy view layout was confusing
New layout and improved logic: user can either enter geo location manually or getting automatic location
> Improved geo location question view (connect #673)

- .travis.yml
- README.md
- app/build.gradle
- app/src/androidTest/java/org/akvo/flow/activity/FreeTextSurveyTest.java
- app/src/test/java/org/akvo/flow/util/StringUtilTest.java
- build.gradle
- config/checkstyle.xml
- data/build.gradle
- domain/build.gradle
No CI config, manual builds only
Added basic travis CI config:
Travis script includes: run lint, run unit tests for all modules, runs android tests for flow debug configuration for which it creates a coverage report and uploads it to codecov.io: 
https://codecov.io/gh/akvo/akvo-flow-mobile/branch/feature%2F541-travis-config
Added status to readme for both codecov and travis
NA
> basic travis config (connect #541)

- app/src/main/java/org/akvo/flow/ui/view/GeoQuestionView.java
Snackbar disappears too quickly
increased snackbar timeout
NA
> Increased snackbar timeout (connect #675) 

- app/src/main/java/org/akvo/flow/ui/view/GeoInputContainer.java
- app/src/main/java/org/akvo/flow/ui/view/GeoQuestionView.java
Crash see issue
do not parse string altitude as double
do not format altitude value
NA
> Fixed crash with altitude parsing (connect #697)

- domain/src/main/java/org/akvo/flow/domain/entity/DataPoint.java
- domain/src/main/java/org/akvo/flow/domain/entity/SyncResult.java
- domain/src/main/java/org/akvo/flow/domain/exception/AssignmentRequiredException.java
- domain/src/main/java/org/akvo/flow/domain/interactor/GetSavedDataPoints.java
- domain/src/main/java/org/akvo/flow/domain/interactor/SyncDataPoints.java
- domain/src/main/java/org/akvo/flow/domain/repository/SurveyRepository.java
- domain/src/main/java/org/akvo/flow/domain/util/ConnectivityStateManager.java
NA
All the classes necessary for syncing and retrieving datapoints inside the domain module.
For now they are unused.
**Phase 1** for separating the big PR #638 
NA
> Created base classes for datapoint sync 1/6 (connect #583)

- app/src/main/java/org/akvo/flow/ui/fragment/DrawerFragment.java
- app/src/main/res/color/tab_text_color.xml
- app/src/main/res/layout/navigation_drawer.xml
The survey when selected had a grey background
remove the grey background as requested on the issue
NA
> Remove list grey selector from survey list item (connect #704)

- app/src/main/java/org/akvo/flow/activity/SettingsActivity.java
- app/src/main/res/values-es/strings.xml
- app/src/main/res/values-fr/strings.xml
- app/src/main/res/values-hi/strings.xml
- app/src/main/res/values-in/strings.xml
- app/src/main/res/values-km/strings.xml
- app/src/main/res/values-ne/strings.xml
- app/src/main/res/values-pt/strings.xml
- app/src/main/res/values-vi/strings.xml
Release build lint reported problems
Followed the recommended actions; removed the unused strings and made the call with the application context.
> Issue/712 code and trans cleanup (Connect #712)

- app/src/main/java/org/akvo/flow/activity/FormActivity.java
Crash when trying to open form activity but the form is not found
If the activity is going to be closed, skip the initialisation code
Added error toast to show user something wrong with forms
NA
> Fixed NPE when error finding form (connect #637)

- app/src/main/java/org/akvo/flow/activity/SurveyActivity.java
Pressing back when drawer is opened closes the app
Now pressing back when drawer is opened, closes drawer
NA
> Fixed drawer back navigation (connect #711)

- app/src/main/java/org/akvo/flow/ui/fragment/DrawerFragment.java
Some forms were really stuck to the border of the view (see issue for screenshot)
Added a right padding
NA
> Long form names padding (connect #727)

- app/src/main/java/org/akvo/flow/activity/FormActivity.java
- app/src/main/java/org/akvo/flow/activity/GeoshapeActivity.java
- app/src/main/java/org/akvo/flow/activity/MapActivity.java
- app/src/main/java/org/akvo/flow/activity/RecordActivity.java
- app/src/main/java/org/akvo/flow/activity/SurveyActivity.java
- app/src/main/java/org/akvo/flow/activity/TransmissionHistoryActivity.java
- app/src/main/java/org/akvo/flow/data/database/SurveyDbAdapter.java
- app/src/main/java/org/akvo/flow/injector/component/ViewComponent.java
- app/src/main/java/org/akvo/flow/injector/module/ViewModule.java
- app/src/main/java/org/akvo/flow/presentation/BaseActivity.java
- app/src/main/java/org/akvo/flow/ui/Navigator.java
- app/src/main/java/org/akvo/flow/ui/adapter/RecordTabsAdapter.java
- app/src/main/java/org/akvo/flow/ui/adapter/ResponseListAdapter.java
- app/src/main/java/org/akvo/flow/ui/fragment/DatapointsFragment.java
- app/src/main/java/org/akvo/flow/ui/fragment/FormListFragment.java
- app/src/main/java/org/akvo/flow/ui/fragment/MapFragment.java
- app/src/main/java/org/akvo/flow/ui/fragment/RecordListListener.java
- app/src/main/java/org/akvo/flow/ui/fragment/ResponseListFragment.java
- app/src/main/java/org/akvo/flow/ui/fragment/SurveyedLocaleListFragment.java
- app/src/main/java/org/akvo/flow/ui/view/GeoshapeQuestionView.java
- app/src/main/java/org/akvo/flow/util/ConstantUtil.java
For some reason there was a crash when trying to view a datapoint that has been deleted. Not sure how it is triggered.
Cleaned up all the params passed to the RecordActivity and FormActivity. 
Checking for record not being null before setting the RecordActivity title.
NA
> Fixed crash in RecordActivity (connect #655)

- app/src/main/java/org/akvo/flow/data/CascadeDB.java
Crash reported by sentry related to cascade database being null
check for null before attempting access cascade node + a bit of class clean up
NA
> Fixed crash when database is null (connect #716)

- app/src/main/java/org/akvo/flow/domain/ValidationRule.java
- app/src/main/java/org/akvo/flow/util/ConstantUtil.java
Useless rule laying around
removed rule.
NA
> Removed name validation (connect #709)

- app/build.gradle
- app/src/main/AndroidManifest.xml
- app/src/main/java/org/akvo/flow/activity/FormActivity.java
- app/src/main/java/org/akvo/flow/activity/SignatureActivity.java
- app/src/main/java/org/akvo/flow/domain/response/value/Signature.java
- app/src/main/java/org/akvo/flow/presentation/signature/SignatureActivity.java
- app/src/main/java/org/akvo/flow/ui/Navigator.java
- app/src/main/java/org/akvo/flow/ui/view/QuestionGroupTab.java
- app/src/main/java/org/akvo/flow/ui/view/SignatureQuestionView.java
- app/src/main/java/org/akvo/flow/ui/view/signature/SignatureQuestionView.java
- app/src/main/java/org/akvo/flow/ui/view/signature/SignatureView.java
- app/src/main/java/org/akvo/flow/util/ConstantUtil.java
- app/src/main/java/org/akvo/flow/util/ImageUtil.java
- app/src/main/java/org/akvo/flow/util/ViewUtil.java
- app/src/main/java/org/akvo/flow/util/image/GlideImageLoader.java
- app/src/main/java/org/akvo/flow/util/image/ImageLoader.java
- app/src/main/java/org/akvo/flow/util/image/ImageLoaderListener.java
- app/src/main/res/layout/activity_signature.xml
- app/src/main/res/layout/signature_question_view.xml
- app/src/main/res/values/strings.xml
Fixes needed for Jana's comment:
https://github.com/akvo/akvo-flow-mobile/issues/751#issuecomment-309351402
* from Modify signature to Edit signature
* hide name text field when this one is empty
* display saved signature inside the signature editor view (part 1)
NA
> Signature view fixes (connect #751)

- app/src/main/res/values-es/strings.xml
- app/src/main/res/values-fr/strings.xml
- app/src/main/res/values-hi/strings.xml
- app/src/main/res/values-in/strings.xml
- app/src/main/res/values-km/strings.xml
- app/src/main/res/values-ne/strings.xml
- app/src/main/res/values-pt/strings.xml
- app/src/main/res/values-vi/strings.xml
NA
Pull latest translations from transifex
NA
> update translations (connect #762)

- app/src/main/java/org/akvo/flow/ui/fragment/DrawerFragment.java
The drawer fragment was not updated when survey was deleted or a new one selected
make sure the drawer ui also gets updated
NA
> Update drawer fragment when survey deleted/selected (connect #767)

- app/src/main/java/org/akvo/flow/util/logging/RavenEventBuilderHelper.java
- app/src/main/java/org/akvo/flow/util/logging/TagsFactory.java
the release info is missing from latest releases as the previous library was sending it https://sentry.io/akvo-foundation/flow-android/releases/
sending release info (version.name)
NA
> Sending release info to sentry (connect #777)

- app/src/main/java/org/akvo/flow/ui/view/signature/SignatureDrawView.java
Issue found by Jana while testing
Fixed unable to save editeted name in a saved signature
NA
> Fixed unable to save edited text of a saved signature (connect #751)

- app/src/main/java/org/akvo/flow/activity/SurveyActivity.java
Fab was shown also for non-monitored forms
Hide fab for non monitored-forms
> Fixed fab displayed for non monitored forms (connect #796)

- app/src/main/java/org/akvo/flow/activity/SettingsActivity.java
- app/src/main/res/values/strings.xml
Wifi can be switched off from our settings which is not necessary and may be even confusing.
Removed that setting
NA
> Removed wifi toggle (connect #795)

- app/src/main/java/org/akvo/flow/activity/SettingsActivity.java
- app/src/main/java/org/akvo/flow/activity/SurveyActivity.java
- app/src/main/java/org/akvo/flow/injector/component/ViewComponent.java
- app/src/main/java/org/akvo/flow/ui/Navigator.java
- app/src/main/java/org/akvo/flow/ui/fragment/DrawerFragment.java
- app/src/main/res/values/strings.xml
About page access from settings
About page can now be accessed from hamburger menu
> About page access (connect #771)

- app/src/main/java/org/akvo/flow/activity/FormActivity.java
- app/src/main/java/org/akvo/flow/data/database/SurveyDbDataSource.java
- app/src/main/java/org/akvo/flow/domain/Question.java
- app/src/main/java/org/akvo/flow/ui/view/MediaQuestionView.java
- app/src/main/java/org/akvo/flow/ui/view/QuestionGroupTab.java
Repeated groups are not displayed 
Fix the ui to use the new params added to database separating questionId and iteration columns
NA
> Fix ui display repeated groups (connect #600)

- app/src/main/java/org/akvo/flow/injector/module/ApplicationModule.java
- app/src/main/java/org/akvo/flow/presentation/datapoints/list/DataPointListAdapter.java
- app/src/main/java/org/akvo/flow/presentation/datapoints/list/DataPointsListPresenter.java
- data/build.gradle
- database/build.gradle
- database/src/main/java/org/akvo/flow/database/britedb/BriteSurveyDbAdapter.java
- domain/build.gradle
Sometimes the wrong datapoints were briefly displayed for the wrong survey
make sure we unsubscribe before loading new datapoints
added error logging when the wrong survey group is displayed to catch the error in sentry
NA
> Fixed wrong datapoints displayed (connect #841)

- .travis.yml
- app/src/main/java/org/akvo/flow/ui/view/MediaQuestionView.java
- app/src/main/java/org/akvo/flow/util/image/GlideImageLoader.java
- app/src/main/java/org/akvo/flow/util/image/ImageLoader.java
Portrait images are displayed wrong on devices with android < 7.0
Use the glide library to display images correctly
NA
> Display images correctly (connect #832)

- app/src/main/res/values/arrays.xml
The dutch translations were added but not in the settings list
Add dutch language to the translations array for the app settings
> Added dutch also to settings arrays (connect #812)

- .travis.yml
Travis builds broken after merging changes from test issue #613 
Fixed travis builds
NA
> Using android-21 instead of -19 (connect #858)

- app/src/main/java/org/akvo/flow/activity/BackActivity.java
> Fixed slow back response back navigation on some devices (connect #863)

- app/src/main/java/org/akvo/flow/activity/SettingsActivity.java
- app/src/main/java/org/akvo/flow/ui/Navigator.java
- app/src/main/res/values/strings.xml
> improve device storage settings display (connect #803)

- data/src/main/java/org/akvo/flow/data/datasource/preferences/SharedPreferencesDataSource.java
- data/src/main/java/org/akvo/flow/data/repository/UserDataRepository.java
- domain/src/main/java/org/akvo/flow/domain/entity/UserSettings.java
- domain/src/main/java/org/akvo/flow/domain/interactor/GetUserSettings.java
- domain/src/main/java/org/akvo/flow/domain/interactor/SaveAppLanguage.java
- domain/src/main/java/org/akvo/flow/domain/interactor/SaveEnableMobileData.java
- domain/src/main/java/org/akvo/flow/domain/interactor/SaveImageSize.java
- domain/src/main/java/org/akvo/flow/domain/interactor/SaveKeepScreenOn.java
- domain/src/main/java/org/akvo/flow/domain/repository/UserRepository.java
The preferences are not very well organized
Organise the settings in a more logic way, remove some useless functionalities, redesign
This is the first part and the data and domain logic only is added, the ui changes are in part2
NA
> Part1: Added logic to data and domain for new preferences (connect #501) 

- app/src/main/java/org/akvo/flow/app/FlowApp.java
- app/src/main/res/values/styles.xml
2 points needed to be fixed for the #501 
Have the spinner entry in black so it does not look as disabled
Fix issue of language not being updated with a restart of the app
NA
> Fixes for settings (connect #501)

- app/src/main/res/values-es/strings.xml
- app/src/main/res/values-fr/strings.xml
- app/src/main/res/values-hi/strings.xml
- app/src/main/res/values-in/strings.xml
- app/src/main/res/values-km/strings.xml
- app/src/main/res/values-ne/strings.xml
- app/src/main/res/values-nl/strings.xml
- app/src/main/res/values-pt/strings.xml
- app/src/main/res/values-vi/strings.xml
Outdated translations
pulled latest strings
NA
> Latest strings (connect #855) 

- app/src/main/java/org/akvo/flow/activity/GeoshapeActivity.java
- app/src/main/java/org/akvo/flow/presentation/geoshape/DeletePointConfirmationDialog.java
- app/src/main/java/org/akvo/flow/presentation/geoshape/DeletePointDialog.java
- app/src/main/java/org/akvo/flow/presentation/geoshape/DeleteShapeDialog.java
- app/src/main/res/values/strings.xml
Geoshape dialogs are confusing
simplify geoshape delete dialogs
NA
> geoshape dialog (connect #787)

- data/src/main/java/org/akvo/flow/data/repository/SurveyDataRepository.java
Wrong way to use exceptions in rxjava
fixed the issue so now the user will see the correct error message
NA
> Fixed exception thrown in a wrong way with rxjava (connect #895)

- app/src/main/java/org/akvo/flow/data/database/QuestionResponseColumns.java
- app/src/main/java/org/akvo/flow/data/database/SurveyDbDataSource.java
- database/src/main/java/org/akvo/flow/database/SurveyDbAdapter.java
Prefiling questions does not work
Fix issue when prefiling questions, the questionId was null + remove code duplication related to response retrieving
> prefill not working (connect #904)

- app/src/main/res/values-es/strings.xml
- app/src/main/res/values-fr/strings.xml
- app/src/main/res/values-hi/strings.xml
- app/src/main/res/values-in/strings.xml
- app/src/main/res/values-km/strings.xml
- app/src/main/res/values-ne/strings.xml
- app/src/main/res/values-nl/strings.xml
- app/src/main/res/values-pt/strings.xml
- app/src/main/res/values-vi/strings.xml
> Pulled latest translations (connect #909)

- domain/src/main/java/org/akvo/flow/domain/interactor/GetSavedDataPoints.java
When making a search, only part of the id is searched
the id has to be returned even if the string searched is not at the beginning of the id
NA
> Search fix (connect #752)

- app/src/main/AndroidManifest.xml
App flickering appears after language is changed
Fix the app flickering for all the affected activities
NA
> Fixed app flickering (connect #847)

- .travis.yml
- app/build.gradle
- build.gradle
- data/build.gradle
- database/build.gradle
- domain/build.gradle
- gradle/wrapper/gradle-wrapper.properties
NA
The latest android studio update required some changes in the build files
NA
> build config changes after studio update (connect #913)

- app/src/main/java/org/akvo/flow/presentation/datapoints/DataPointSyncSnackBarManager.java
- app/src/main/java/org/akvo/flow/presentation/datapoints/list/DataPointsListFragment.java
- app/src/main/java/org/akvo/flow/presentation/datapoints/list/DataPointsListPresenter.java
- app/src/main/java/org/akvo/flow/presentation/datapoints/list/DataPointsListView.java
- app/src/main/java/org/akvo/flow/presentation/datapoints/map/DataPointsMapFragment.java
- app/src/main/java/org/akvo/flow/presentation/datapoints/map/DataPointsMapPresenter.java
- app/src/main/java/org/akvo/flow/presentation/datapoints/map/DataPointsMapView.java
- app/src/main/res/values/strings.xml
Nothing shown when there are no datapoints to sync
Display a SnackBar saying there is nothing to sync
NA
> Added SnackBar when there are no datapoints to sync (connect #922)

- app/src/androidTest/java/org/akvo/flow/activity/FreeTextFormActivityViewTest.java
- app/src/androidTest/java/org/akvo/flow/activity/MultiItemByPositionMatcher.java
- app/src/androidTest/java/org/akvo/flow/activity/RepeatedGroupFreeTextFormActivityViewTest.java
- app/src/androidTest/java/org/akvo/flow/activity/testhelper/SurveyInstaller.java
- app/src/androidTest/res/raw/repeated_groups_survey.xml
- app/src/main/java/org/akvo/flow/ui/view/QuestionGroupTab.java
- app/src/main/res/layout/question_group_tab.xml
Lacking tests for displaying existing answers
Added tests for view free text question and repeated question groups: one has barcodes and the other text
NA
> Response view tests (connect #907)

- app/src/main/AndroidManifest.xml
- app/src/main/java/org/akvo/flow/activity/SurveyActivity.java
- app/src/main/java/org/akvo/flow/app/FlowApp.java
- app/src/main/java/org/akvo/flow/broadcast/BootStrapReceiver.java
- app/src/main/java/org/akvo/flow/injector/component/ApplicationComponent.java
- app/src/main/java/org/akvo/flow/service/BootstrapService.java
- app/src/main/java/org/akvo/flow/service/FileChangeTrackingService.java
- app/src/main/java/org/akvo/flow/service/FileChangeTrackingServiceApi6.java
- app/src/main/java/org/akvo/flow/service/ZipFileLister.java
- app/src/main/java/org/akvo/flow/util/ConstantUtil.java
User has to restart the app for bootstrap files to be taken into account.
bootstrap files will be tracked and when a new one appears we should start the BootstrapService
NA
> trigger survey bootstrap (connect #635)

- app/src/androidTest/java/org/akvo/flow/activity/AddUserActivityTest.java
NA
While creating the form activity tests, had to run those test so decided to add them
NA
> Add user tests (connect #936)

- app/build.gradle
- app/src/androidTest/java/org/akvo/flow/activity/RepeatedGroupFreeTextFormActivityViewTest.java
- app/src/main/java/org/akvo/flow/activity/FormActivity.java
- app/src/main/java/org/akvo/flow/ui/view/CaddisflyQuestionView.java
- app/src/main/java/org/akvo/flow/ui/view/CascadeQuestionView.java
- app/src/main/java/org/akvo/flow/ui/view/FreetextQuestionView.java
- app/src/main/java/org/akvo/flow/ui/view/MediaQuestionView.java
- app/src/main/java/org/akvo/flow/ui/view/QuestionGroupTab.java
- app/src/main/java/org/akvo/flow/ui/view/QuestionHeaderView.java
- app/src/main/java/org/akvo/flow/ui/view/QuestionView.java
- app/src/main/java/org/akvo/flow/ui/view/SubmitTab.java
- app/src/main/java/org/akvo/flow/ui/view/barcode/BarcodeQuestionInput.java
- app/src/main/java/org/akvo/flow/ui/view/barcode/BarcodeQuestionViewMultiple.java
- app/src/main/java/org/akvo/flow/ui/view/barcode/BarcodeQuestionViewReadOnly.java
- app/src/main/java/org/akvo/flow/ui/view/barcode/BarcodeViewHolder.java
- app/src/main/java/org/akvo/flow/ui/view/option/OptionQuestionView.java
- app/src/main/java/org/akvo/flow/ui/view/signature/SignatureQuestionView.java
- app/src/main/java/org/akvo/flow/util/PlatformUtil.java
- app/src/main/res/layout/barcode_item.xml
- app/src/main/res/layout/barcode_question_input.xml
- app/src/main/res/layout/barcode_question_view_multiple.xml
- app/src/main/res/layout/caddisfly_question_view.xml
- app/src/main/res/layout/cascading_level_item.xml
- app/src/main/res/layout/geoshape_question_view.xml
- app/src/main/res/layout/invalid_question_view.xml
- app/src/main/res/layout/media_question_view.xml
- app/src/main/res/layout/signature_question_view.xml
- app/src/main/res/values/ids.xml
NA
Added ids and tags to better detect views in the tests
NA
> Added changes to app ui ids for tests (connect #930)

- app/src/androidTest/java/org/akvo/flow/activity/form/emptyformsview/FormActivityTest.java
- app/src/androidTest/java/org/akvo/flow/activity/form/formsview/FormActivityTest.java
Added the empty forms viewing tests class. It tests all the possible form questions to make sure they are displayed correctly. This does not test actual form filling or displaying of filled forms
> Forms viewing test (connect #930)

- app/src/main/java/org/akvo/flow/activity/FormActivity.java
- app/src/main/java/org/akvo/flow/ui/view/MediaQuestionView.java
- app/src/main/java/org/akvo/flow/ui/view/signature/SignatureQuestionView.java
- app/src/main/java/org/akvo/flow/util/MediaFileHelper.java
- app/src/main/java/org/akvo/flow/util/image/Base64RequestHandler.java
- app/src/main/java/org/akvo/flow/util/image/ImageLoader.java
- app/src/main/java/org/akvo/flow/util/image/PicassoImageLoader.java
- app/src/main/java/org/akvo/flow/util/image/VideoRequestHandler.java
Improve the way videos url is used, improve load of some images resources.
> Fixed issue with video recording not working on some devices (connect #612)

- .travis.yml
- app/src/androidTest/java/org/akvo/flow/activity/OptionsFormActivityTest.java
- app/src/main/java/org/akvo/flow/ui/view/CaddisflyQuestionView.java
- app/src/main/java/org/akvo/flow/ui/view/DateQuestionView.java
- app/src/main/java/org/akvo/flow/ui/view/FreetextQuestionView.java
- app/src/main/java/org/akvo/flow/ui/view/MediaQuestionView.java
- app/src/main/java/org/akvo/flow/ui/view/geolocation/GeoInputContainer.java
- app/src/main/java/org/akvo/flow/ui/view/geolocation/GeoQuestionView.java
- app/src/main/java/org/akvo/flow/ui/view/signature/SignatureQuestionView.java
Removed useless disabled buttons when viewing filled forms
> read-only responses view (connect #949)

- app/build.gradle
- app/src/main/java/org/akvo/flow/presentation/AboutActivity.java
2017 hardcoded
Use calendar and current year to display the year to the user.
NA
> Updating copyright year displayed to the user (connect #980) 

- app/src/main/java/org/akvo/flow/activity/AppUpdateActivity.java
- app/src/main/java/org/akvo/flow/injector/component/ViewComponent.java
- app/src/main/java/org/akvo/flow/ui/Navigator.java
- app/src/main/java/org/akvo/flow/util/FileUtil.java
- app/src/main/java/org/akvo/flow/util/PlatformUtil.java
- app/src/main/java/org/akvo/flow/util/files/ApkFileBrowser.java
- app/src/main/java/org/akvo/flow/util/files/FileBrowser.java
- app/src/main/java/org/akvo/flow/util/files/FormFileBrowser.java
- app/src/main/res/values/strings.xml
- app/src/test/java/org/akvo/flow/util/files/ApkFileBrowserTest.java
Please merge https://github.com/akvo/akvo-flow-mobile/pull/966 first
Moved apk files to public app dedicated folder + added unit tests
NA
> public app dedicated storage for apk folders (connect #968)

- app/src/main/res/values-es/strings.xml
- app/src/main/res/values-fr/strings.xml
- app/src/main/res/values-hi/strings.xml
- app/src/main/res/values-in/strings.xml
- app/src/main/res/values-km/strings.xml
- app/src/main/res/values-ne/strings.xml
- app/src/main/res/values-nl/strings.xml
- app/src/main/res/values-pt/strings.xml
- app/src/main/res/values-vi/strings.xml
New strings have been translated
Pull latests strings available
NA
> Pulled latest strings (connect #985)

- app/src/main/java/org/akvo/flow/activity/FormActivity.java
- app/src/main/java/org/akvo/flow/ui/view/geolocation/GeoFieldsResetConfirmDialogFragment.java
- app/src/main/java/org/akvo/flow/ui/view/geolocation/GeoQuestionView.java
- app/src/main/java/org/akvo/flow/util/ConstantUtil.java
- app/src/main/res/values/strings.xml
GPS data may be reset by error if the user presses the button by mistake.
If there are already existing gps coordinates, display a dialog to confirm user wants to delete existing coordinates and get new ones.
> Confirm geo overwrite (connect #981) 

- app/src/main/AndroidManifest.xml
- app/src/main/java/org/akvo/flow/ui/fragment/DrawerFragment.java
- app/src/main/res/layout/activity_preference.xml
- app/src/main/res/values-es/strings.xml
- app/src/main/res/values-fr/strings.xml
- app/src/main/res/values-in/strings.xml
- app/src/main/res/values-ne/strings.xml
- app/src/main/res/values-nl/strings.xml
- app/src/main/res/values-pt/strings.xml
- app/src/main/res/values-vi/strings.xml
- app/src/main/res/values/strings.xml
NA
Small changes to app settings title and section title as agreed on the issue
NA
> App settings updated title and section title (connect #940)

- app/build.gradle
- app/src/androidTest/java/org/akvo/flow/activity/OptionsFormActivityTest.java
- app/src/main/java/org/akvo/flow/app/FlowApp.java
- app/src/main/java/org/akvo/flow/event/TimedLocationListener.java
- app/src/main/java/org/akvo/flow/presentation/datapoints/list/DataPointsListFragment.java
- app/src/main/java/org/akvo/flow/util/WeakLocationListener.java
Users complained app was crashing a lot which seemed due to running out of memory.
Added leak canary tool + run tests + found 2 leaks -> solved the leaks
NA
> Leak canary (connect #850)

- app/src/main/res/values-es/strings.xml
- app/src/main/res/values-fr/strings.xml
- app/src/main/res/values-hi/strings.xml
- app/src/main/res/values-in/strings.xml
- app/src/main/res/values-km/strings.xml
- app/src/main/res/values-ne/strings.xml
- app/src/main/res/values-nl/strings.xml
- app/src/main/res/values-pt/strings.xml
- app/src/main/res/values-vi/strings.xml
> Pull latest strings (connect #1013)

- app/src/main/java/org/akvo/flow/presentation/EditUserDialog.java
- app/src/main/java/org/akvo/flow/presentation/UserDeleteConfirmationDialog.java
- app/src/main/java/org/akvo/flow/presentation/navigation/CreateUserDialog.java
- app/src/main/java/org/akvo/flow/presentation/navigation/SurveyDeleteConfirmationDialog.java
- app/src/main/java/org/akvo/flow/presentation/navigation/UserMapper.java
- app/src/main/java/org/akvo/flow/presentation/navigation/ViewUser.java
- app/src/main/java/org/akvo/flow/util/ConstantUtil.java
> Part 4: Navigation drawer refactor (connect #670)

- app/src/main/java/org/akvo/flow/service/ApkUpdateService.java
- app/src/main/java/org/akvo/flow/service/FileChangeTrackingService.java
> Fixed NPE in gcm tasks when intent is null (connect #1021)

- app/src/main/java/org/akvo/flow/presentation/datapoints/list/DataPointsListFragment.java
- app/src/main/java/org/akvo/flow/presentation/datapoints/list/DataPointsListPresenter.java
- app/src/main/java/org/akvo/flow/presentation/datapoints/list/DataPointsListView.java
- app/src/main/java/org/akvo/flow/presentation/datapoints/map/DataPointsMapFragment.java
- app/src/main/java/org/akvo/flow/presentation/datapoints/map/DataPointsMapPresenter.java
- app/src/main/java/org/akvo/flow/presentation/datapoints/map/DataPointsMapView.java
Menu not displayed correctly when no survey selected
When no survey is selected we have to hide the menu
NA
> Fix menu not displayed correctly (connect #1027)

- app/src/main/java/org/akvo/flow/presentation/datapoints/map/DataPointsMapFragment.java
PLEASE merge https://github.com/akvo/akvo-flow-mobile/pull/1029 first
centerMap method has issues: NPE, too many useless comments
Add null check
remove comments
using application context to avoid leaks
better name
NA
> Center map method (connect #1028)

- app/src/main/java/org/akvo/flow/presentation/navigation/RecyclerItemClickListener.java
- app/src/main/java/org/akvo/flow/presentation/navigation/SurveyAdapter.java
- app/src/main/java/org/akvo/flow/presentation/navigation/UserAdapter.java
- app/src/main/res/layout/navigation_item.xml
- app/src/main/res/layout/survey_activity.xml
- app/src/main/res/values/styles.xml
selecting users and surveys is hard
Improve selected area + provide feedback to user on selection (greyed out area)
NA
> Improved survey and user selection (connect #1031)

- database/src/main/res/values/languages.xml
The 2 newly added languages Tok Pisin and Solomon Islands Pijin are not visible in the app as we need to add them to the list manually.
Added 2 new languages and language codes
NA
> Added 2 new languages (connect #1062)

- app/src/main/java/org/akvo/flow/activity/FormActivity.java
- app/src/main/java/org/akvo/flow/activity/RecordActivity.java
- app/src/main/java/org/akvo/flow/activity/SurveyActivity.java
- app/src/main/java/org/akvo/flow/ui/Navigator.java
- app/src/main/java/org/akvo/flow/ui/view/SubmitTab.java
- app/src/main/java/org/akvo/flow/util/ConstantUtil.java
- app/src/main/res/layout/record_activity.xml
- app/src/main/res/layout/submit_button.xml
- app/src/main/res/layout/survey_activity_content.xml
- app/src/main/res/values/ids.xml
- app/src/main/res/values/strings.xml
After pressing the submit button inside a form, there is a strange dialog which has no value
Remove the dialog
Clarify the submit description
Display a snackbar after form was successfully submitted
> Form submission screen (connect #617)

- app/src/main/java/org/akvo/flow/api/service/ApkApiService.java
Backend does not know which android version the device has
Send the android version
NA
> Sending androidBuildVersion to backend (connect #1091)

- app/src/main/java/org/akvo/flow/presentation/main/MainPresenter.java
- app/src/main/java/org/akvo/flow/presentation/main/MainView.java
- app/src/main/java/org/akvo/flow/presentation/walkthrough/WalkthroughPresenter.java
- app/src/main/java/org/akvo/flow/presentation/walkthrough/WalkthroughView.java
- data/src/main/java/org/akvo/flow/data/datasource/preferences/SharedPreferencesDataSource.java
- data/src/main/java/org/akvo/flow/data/repository/UserDataRepository.java
- domain/src/main/java/org/akvo/flow/domain/interactor/GetIsDeviceSetUp.java
- domain/src/main/java/org/akvo/flow/domain/interactor/SetWalkthroughSeen.java
- domain/src/main/java/org/akvo/flow/domain/interactor/WasWalkthroughSeen.java
- domain/src/main/java/org/akvo/flow/domain/repository/UserRepository.java
NA
We need to inform the users the collected data files have been moved to private storage and they can be exported.
This part 1 of the walkthrough i about adding the logic
NA
> Walthrough part 1: domain, data and presentation logic (connect #984)

- data/build.gradle
- data/src/main/java/org/akvo/flow/data/datasource/FileDataSource.java
- data/src/main/java/org/akvo/flow/data/datasource/FolderBrowser.java
- data/src/main/java/org/akvo/flow/data/repository/FileDataRepository.java
- domain/src/main/java/org/akvo/flow/domain/interactor/PublishData.java
- domain/src/main/java/org/akvo/flow/domain/repository/FileRepository.java
> Move published files (connect #1080)

- app/src/main/java/org/akvo/flow/presentation/walkthrough/WalkThrough1Fragment.java
- app/src/main/java/org/akvo/flow/presentation/walkthrough/WalkThrough2Fragment.java
- app/src/main/java/org/akvo/flow/presentation/walkthrough/WalkThroughActivity.java
- app/src/main/res/layout/activity_walkthrough.xml
- app/src/main/res/layout/walkthrough_fragment_page1.xml
- app/src/main/res/layout/walkthrough_fragment_page2.xml
Buttons were displayed above the pager dots (contrary to design specs)
Made buttons below the paging dots
NA
> Fixed walkthrough buttons positioning (connect #984)

- app/src/main/res/values-es/strings.xml
- app/src/main/res/values-fr/strings.xml
- app/src/main/res/values-hi/strings.xml
- app/src/main/res/values-in/strings.xml
- app/src/main/res/values-km/strings.xml
- app/src/main/res/values-ne/strings.xml
- app/src/main/res/values-nl/strings.xml
- app/src/main/res/values-pt/strings.xml
- app/src/main/res/values-vi/strings.xml
NA
Pulled latest translations
NA
> Pulled latest translations (connect #1119)

- app/src/main/java/org/akvo/flow/ui/Navigator.java
- app/src/main/java/org/akvo/flow/ui/view/media/photo/PhotoQuestionPresenter.java
- app/src/main/java/org/akvo/flow/ui/view/media/photo/PhotoQuestionView.java
- app/src/main/java/org/akvo/flow/ui/view/media/video/VideoQuestionPresenter.java
- app/src/main/java/org/akvo/flow/ui/view/media/video/VideoQuestionView.java
- app/src/main/java/org/akvo/flow/util/MediaFileHelper.java
When we had saved forms with images, after moving files to private folder, these files paths were not updated and they were lost.
Always rebuild the file path using the filename
NA
> Media file paths (connect #1130)

- app/src/main/java/org/akvo/flow/ui/Navigator.java
> remove unused method (connect #1143)

- data/src/main/java/org/akvo/flow/data/datasource/FileDataSource.java
- data/src/main/java/org/akvo/flow/data/datasource/FolderBrowser.java
- data/src/main/java/org/akvo/flow/data/repository/FileDataRepository.java
- data/src/main/java/org/akvo/flow/data/repository/SurveyDataRepository.java
- database/src/main/java/org/akvo/flow/database/SurveyDbAdapter.java
- database/src/main/java/org/akvo/flow/database/britedb/BriteSurveyDbAdapter.java
Data syncing and exporting logic all in one class, need refactor to be able to reuse the code in several places.
refactor part 2: Mostly database module changes +  some data source related logic (data module)
Note: the project does not build as this is only one part of the solution
You can see the final solution https://github.com/akvo/akvo-flow-mobile/pull/1142
NA
> Part 2: Refactor datapoint export and sync (connect #1152)

- data/src/main/java/org/akvo/flow/data/net/FlowRestApi.java
- data/src/main/java/org/akvo/flow/data/net/HMACInterceptor.java
- data/src/main/java/org/akvo/flow/data/net/RestServiceFactory.java
- data/src/main/java/org/akvo/flow/data/net/S3User.java
- data/src/main/java/org/akvo/flow/data/net/SignatureHelper.java
- data/src/main/java/org/akvo/flow/data/net/gae/DataPointDownloadService.java
- data/src/main/java/org/akvo/flow/data/net/gae/DeviceFilesService.java
- data/src/main/java/org/akvo/flow/data/net/gae/ProcessingNotificationService.java
- data/src/main/java/org/akvo/flow/data/net/s3/AwsS3.java
data sync refactor
Refactor part 4: data net package
Note: the project does not build as this is only one part of the solution
You can see the final solution #1142
NA
> Part 4: Added data module net package changes (connect #1152)

- app/src/main/java/org/akvo/flow/activity/FormActivity.java
- app/src/main/java/org/akvo/flow/ui/view/media/photo/PhotoQuestionView.java
- app/src/main/java/org/akvo/flow/ui/view/media/video/IVideoQuestionView.java
- app/src/main/java/org/akvo/flow/ui/view/media/video/VideoQuestionPresenter.java
- app/src/main/java/org/akvo/flow/ui/view/media/video/VideoQuestionView.java
- app/src/main/java/org/akvo/flow/util/ConstantUtil.java
- app/src/main/java/org/akvo/flow/util/MediaFileHelper.java
- data/src/main/java/org/akvo/flow/data/datasource/DataSourceFactory.java
- data/src/main/java/org/akvo/flow/data/datasource/FileDataSource.java
- data/src/main/java/org/akvo/flow/data/datasource/FlowFileBrowser.java
- data/src/main/java/org/akvo/flow/data/datasource/ImageDataSource.java
- data/src/main/java/org/akvo/flow/data/datasource/MediaDataSource.java
- data/src/main/java/org/akvo/flow/data/repository/FileDataRepository.java
- data/src/main/java/org/akvo/flow/data/util/ImageSize.java
- domain/src/main/java/org/akvo/flow/domain/interactor/CopyVideo.java
- domain/src/main/java/org/akvo/flow/domain/repository/FileRepository.java
Video files were added to device library (without being able to view them)
Removed the duplicated file and notify media content provider
NA
> Remove duplicated video file from library (connect #1145)

- app/build.gradle
- app/src/main/java/org/akvo/flow/util/logging/FlowSentryHttpConnection.java
- build.gradle
Using outdated sentry sdk
update to latest
NA
> sentry update to version 1.7.5 (connect #1083)

- app/src/main/java/org/akvo/flow/ui/view/geolocation/GeoQuestionView.java
geocode was generated and stored in device db 
remove geocode
NA
> Stop storing geocode (connect #990)

- app/src/androidTest/java/org/akvo/flow/activity/form/FormActivityTestUtil.java
- app/src/androidTest/java/org/akvo/flow/activity/form/formfill/DateQuestionViewTest.java
- app/src/androidTest/java/org/akvo/flow/activity/form/formsview/FormActivityTest.java
- app/src/androidTest/java/org/akvo/flow/activity/form/submittedformsview/FormActivityReadOnlyTest.java
- app/src/main/java/org/akvo/flow/ui/view/DateQuestionView.java
- app/src/main/res/layout/date_question_view.xml
date ui is a bit confusing
hide the text input fields and only display it once a date has been set
NA
> date ui improvement (connect #1074)

- .travis.yml
- app/src/androidTest/java/org/akvo/flow/activity/form/formsview/FormActivityTest.java
- app/src/main/java/org/akvo/flow/ui/view/SubmitTab.java
- app/src/main/java/org/akvo/flow/ui/view/geolocation/GeoQuestionView.java
Invalid location can still be submitted
Prevent submission of invalid coordinates
NA
> Prevent submission if geo location fields are not valid (connect #1101)

- data/src/main/java/org/akvo/flow/data/entity/FormInstance.java
- data/src/main/java/org/akvo/flow/data/entity/FormInstanceMapper.java
- database/src/main/java/org/akvo/flow/database/britedb/BriteSurveyDbAdapter.java
form version is not sent with the submission so backend does not know the version of the form for which the submission was made
send form version inside data.json
NA
> Part 10: send form version (connect #1133)

- app/src/androidTest/java/org/akvo/flow/activity/form/FormActivityTestUtil.java
- app/src/androidTest/java/org/akvo/flow/activity/form/formsview/FormActivityTest.java
- app/src/androidTest/java/org/akvo/flow/activity/form/submittedformsview/FormActivityReadOnlyTest.java
- app/src/main/java/org/akvo/flow/activity/FormActivity.java
- app/src/main/java/org/akvo/flow/event/QuestionInteractionEvent.java
- app/src/main/java/org/akvo/flow/injector/module/ViewModule.java
- app/src/main/java/org/akvo/flow/presentation/form/caddisfly/CaddisflyPresenter.java
- app/src/main/java/org/akvo/flow/ui/Navigator.java
- app/src/main/java/org/akvo/flow/ui/view/media/photo/IPhotoQuestionView.java
- app/src/main/java/org/akvo/flow/ui/view/media/photo/PhotoQuestionPresenter.java
- app/src/main/java/org/akvo/flow/ui/view/media/photo/PhotoQuestionView.java
- app/src/main/java/org/akvo/flow/ui/view/media/video/VideoQuestionPresenter.java
- app/src/main/java/org/akvo/flow/ui/view/media/video/VideoQuestionView.java
- app/src/main/java/org/akvo/flow/util/ConstantUtil.java
- app/src/main/java/org/akvo/flow/util/MediaFileHelper.java
- app/src/main/res/layout/media_question_view.xml
- app/src/main/res/values/strings.xml
- app/src/main/res/xml/file_paths.xml
- data/src/main/java/org/akvo/flow/data/datasource/FileDataSource.java
- data/src/main/java/org/akvo/flow/data/datasource/FileHelper.java
- data/src/main/java/org/akvo/flow/data/datasource/ImageDataSource.java
- data/src/main/java/org/akvo/flow/data/datasource/MediaDataSource.java
- data/src/main/java/org/akvo/flow/data/repository/FileDataRepository.java
- domain/src/main/java/org/akvo/flow/domain/interactor/CopyVideo.java
- domain/src/main/java/org/akvo/flow/domain/interactor/SaveResizedImage.java
- domain/src/main/java/org/akvo/flow/domain/repository/FileRepository.java
Photo and Video questions can only be answered by taking a picture or video
Now we can also get a picture or video from the gallery
NA
> browse gallery for pictures and videos on device (connect #1136)

- app/src/main/res/menu/datapoints_list.xml
- app/src/main/res/menu/datapoints_map.xml
Cannot upload non monitoring surveys
Enable datapoint upload for all surveys
NA
> [#1184] Enable upload also for surveys without monitoring (connect #1184)

- app/src/main/java/org/akvo/flow/activity/FormActivity.java
- app/src/main/java/org/akvo/flow/presentation/datapoints/list/DataPointsListPresenter.java
- app/src/main/java/org/akvo/flow/presentation/datapoints/list/DataPointsListView.java
- data/src/main/java/org/akvo/flow/data/datasource/FileDataSource.java
- data/src/main/java/org/akvo/flow/data/datasource/ImageDataSource.java
- database/src/main/java/org/akvo/flow/database/britedb/BriteSurveyDbAdapter.java
Datapoints remained in "saved" state after submission
Make sure datapoints state is correct
Also removed some unused code (had been added post merge)
NA
> [#1152] Fix issue of datapoints status being updated incorrectly (connect #1152)

- fastlane/Fastfile
Deploy fails when there are changes in the branch not present in current branch
pull first
NA
> Issue/1187 deploy fix (connect #1187)

- data/src/main/java/org/akvo/flow/data/datasource/FileDataSource.java
- domain/src/main/java/org/akvo/flow/domain/interactor/CheckSubmittedFiles.java
we check for the zip file in the wrong folder
check for existing zip file in the correct folder
NA
> [#1152] fix issue with zip file not found (connect #1152)

- .gitattributes
if you edit version.properties file in github it gets converted to CRLF
add gitattribute to prevent that
NA
> Create .gitattributes (connect #1194)

- app/src/main/res/values-es/strings.xml
- app/src/main/res/values-fr/strings.xml
- app/src/main/res/values-hi/strings.xml
- app/src/main/res/values-in/strings.xml
- app/src/main/res/values-km/strings.xml
- app/src/main/res/values-ne/strings.xml
- app/src/main/res/values-nl/strings.xml
- app/src/main/res/values-pt/strings.xml
- app/src/main/res/values-vi/strings.xml
Some extra strings are present in translation which produces error messages
Pull latest updated string files from transifex
NA
> Pulled latests strings (connect #1196)

- app/src/androidTest/java/org/akvo/flow/activity/form/FormActivityTestUtil.java
- app/src/androidTest/java/org/akvo/flow/activity/form/formsview/FormActivityTest.java
- app/src/main/java/org/akvo/flow/ui/view/QuestionGroupTab.java
- app/src/main/res/layout/barcode_question_input.xml
- app/src/main/res/layout/caddisfly_question_view.xml
- app/src/main/res/layout/date_question_view.xml
- app/src/main/res/layout/freetext_question_view.xml
- app/src/main/res/layout/geo_question_view.xml
- app/src/main/res/layout/geoshape_question_view.xml
- app/src/main/res/layout/media_question_view.xml
- app/src/main/res/layout/question_group_tab.xml
- app/src/main/res/layout/signature_question_view.xml
- app/src/main/res/layout/submit_tab_footer.xml
- app/src/main/res/values/dimens.xml
- app/src/main/res/values/styles.xml
- app/src/main/res/values/themes.xml
NA
Fixes: 
color accent is now orange
buttons heigh set to wrap content
removed next button
new styling for repeat group button
> [#1103] add improvements to form layout

- app/src/main/AndroidManifest.xml
prevent keyboard covering some content of the screen
> [#1212] Fixes keyboard preventing from eeing parts of the screen (connect #1212)

- app/src/main/java/org/akvo/flow/domain/Question.java
- app/src/main/java/org/akvo/flow/domain/QuestionHelp.java
- app/src/main/java/org/akvo/flow/service/SurveyDownloadService.java
- app/src/main/java/org/akvo/flow/ui/view/QuestionView.java
- app/src/main/java/org/akvo/flow/util/ConstantUtil.java
- app/src/main/res/values/strings.xml
> [#928] Removed video and image help types which were not used (connect #928)

- app/build.gradle
- build.gradle
- data/build.gradle
- database/build.gradle
- domain/build.gradle
some libraries are used in several modules and when we update we need to modify multiple files
add the version to top level file and call it from each build.gradle
NA
> [#845] Extract libraries versions (connect #845)

- app/src/main/java/org/akvo/flow/activity/AddUserActivity.java
- app/src/main/res/values/strings.xml
Empty username and deviceId can be saved if using the keyboard navigation
check for empty fields and display an error message
NA
> [#1211] checking for empty deviceId and username before saving them (connect #1211)

- app/src/main/AndroidManifest.xml
- app/src/main/java/org/akvo/flow/api/FlowApi.java
- app/src/main/java/org/akvo/flow/injector/module/ApplicationModule.java
- app/src/main/java/org/akvo/flow/util/PlatformUtil.java
- app/src/main/java/org/akvo/flow/util/StatusUtil.java
- data/src/main/AndroidManifest.xml
- data/src/main/java/org/akvo/flow/data/net/RestApi.java
- domain/src/main/AndroidManifest.xml
- domain/src/main/java/org/akvo/flow/domain/util/DeviceHelper.java
phone permissions not handled
part 1: check for permission to avoid crashes, this is the first part of the fix
NA
> [#1234] Using DeviceHelper + checking for permissions to avoid crashes (Connect #1234)

- app/src/main/AndroidManifest.xml
- app/src/main/java/org/akvo/flow/activity/BackActivity.java
- app/src/main/java/org/akvo/flow/activity/GeoshapeActivity.java
- app/src/main/java/org/akvo/flow/activity/MapActivity.java
- app/src/main/java/org/akvo/flow/presentation/datapoints/map/DataPointsMapFragment.java
Crashes in location due to runtime permissions missing
if runtime permissions missing just ignore the feature (we awere doing that already)
NA
> Issue/1235 location part1 (Connect #1235)

- app/src/main/java/org/akvo/flow/domain/QuestionResponse.java
- app/src/main/java/org/akvo/flow/event/QuestionInteractionEvent.java
Question was not properly reset when using the "clear" option.
Fixed issue where the previous non deleted value was returned.
NA
> [#1247] Fixed issue where answer was not properly reset (connect #1247)

- app/src/main/java/org/akvo/flow/ui/view/CaddisflyQuestionView.java
- app/src/main/java/org/akvo/flow/util/ConstantUtil.java
NA
Caddisfly needs instance name to do some analytics with the requests. Sending instance name when requesting test from caddislfy
NA
> [#1248] added new field in the caddisfly request bundle (connect #1248)

- app/src/main/java/org/akvo/flow/ui/Navigator.java
using old url for terms
update to new url
> [#1238] updates terms url to new one (connect #1238)

- app/build.gradle
- app/src/main/java/org/akvo/flow/app/FlowApp.java
- build.gradle
debug builds do not work on older devices (android 4)
add the support multidex dependency for debug builds
NA
> [#1254] fix multidex for older devices (connect #1254)

- app/src/main/java/org/akvo/flow/activity/SurveyActivity.java
- app/src/main/java/org/akvo/flow/util/AppPermissionsHelper.java
- app/src/main/java/org/akvo/flow/util/ConstantUtil.java
- app/src/main/res/values/strings.xml
not requesting read phone state permissions when app starts
Read phone state permissions need to be requested
NA
> Issue/1234 read phone state part2 (connect #1234)

- domain/src/main/java/org/akvo/flow/domain/entity/ApkData.java
- domain/src/main/java/org/akvo/flow/domain/interactor/apk/GetApkData.java
- domain/src/main/java/org/akvo/flow/domain/interactor/apk/GetApkDataPreferences.java
- domain/src/main/java/org/akvo/flow/domain/interactor/apk/RefreshApkData.java
- domain/src/main/java/org/akvo/flow/domain/interactor/apk/SaveApkUpdateNotified.java
- domain/src/main/java/org/akvo/flow/domain/repository/ApkRepository.java
- domain/src/main/java/org/akvo/flow/domain/repository/UserRepository.java
- domain/src/main/java/org/akvo/flow/domain/util/GsonMapper.java
- domain/src/main/java/org/akvo/flow/domain/util/VersionHelper.java
NA
Part 1 of the apk update logic refactor: domain logic
NA
> [#537] added apk refactor domain classes (connect #537)

- data/src/main/java/org/akvo/flow/data/datasource/preferences/SharedPreferencesDataSource.java
- data/src/main/java/org/akvo/flow/data/entity/ApiApkData.java
- data/src/main/java/org/akvo/flow/data/entity/ApkDataMapper.java
- data/src/main/java/org/akvo/flow/data/net/RestApi.java
- data/src/main/java/org/akvo/flow/data/net/gae/FlowApiService.java
- data/src/main/java/org/akvo/flow/data/repository/ApkDataRepository.java
- data/src/main/java/org/akvo/flow/data/repository/UserDataRepository.java
- data/src/main/java/org/akvo/flow/data/util/ApiUrls.java
NA
Part 2 of the apk logic refactor: data logic implementation
This is a partial solution and the code does not build
NA
> Issue/537 apk refactor part2 (connect #537)

- app/src/main/java/org/akvo/flow/presentation/about/AboutPresenter.java
- app/src/main/java/org/akvo/flow/presentation/about/AboutView.java
- app/src/main/java/org/akvo/flow/presentation/entity/ViewApkData.java
- app/src/main/java/org/akvo/flow/presentation/entity/ViewApkMapper.java
- app/src/main/java/org/akvo/flow/presentation/survey/SurveyPresenter.java
- app/src/main/java/org/akvo/flow/presentation/survey/SurveyView.java
NA
May not build
Added some of of the new presentation classes to reduce the next PR https://github.com/akvo/akvo-flow-mobile/pull/1263
NA
> [#537] Added new presentation classes (connect #537)

- data/build.gradle
- data/src/main/java/org/akvo/flow/data/datasource/DatabaseDataSource.java
- data/src/main/java/org/akvo/flow/data/entity/FilesResultMapper.java
- data/src/main/java/org/akvo/flow/data/entity/SurveyInstanceIdMapper.java
- data/src/main/java/org/akvo/flow/data/repository/SurveyDataRepository.java
- data/src/test/java/org/akvo/flow/data/entity/FilesResultMapperTest.java
Issues with datapoint status not being updated correctly
changes to the data package and part 1 of the changes
will probably not build
NA
> [#1273] datapoint status improvements changes to data (connect #1273)

- app/src/main/java/org/akvo/flow/api/S3Api.java
- app/src/main/java/org/akvo/flow/injector/module/ApplicationModule.java
- data/src/main/java/org/akvo/flow/data/entity/S3File.java
- data/src/main/java/org/akvo/flow/data/entity/S3FileMapper.java
- data/src/main/java/org/akvo/flow/data/net/RestApi.java
- data/src/main/java/org/akvo/flow/data/net/s3/AmazonAuthHelper.java
- data/src/main/java/org/akvo/flow/data/net/s3/AwsS3.java
- data/src/main/java/org/akvo/flow/data/repository/SurveyDataRepository.java
- data/src/main/java/org/akvo/flow/data/util/FileHelper.java
- data/src/test/java/org/akvo/flow/data/net/s3/AmazonAuthHelperTest.java
Some corrupted files on s3
add a check of the etag sent by s3 in response to file upload
NA
> [#1298] adds verification after sending file to s3 (connect #1298)

- .gitignore
- app/src/main/java/org/akvo/flow/injector/component/ApplicationComponent.java
- app/src/main/java/org/akvo/flow/injector/module/ApplicationModule.java
- app/src/main/java/org/akvo/flow/presentation/datapoints/list/DataPointsListPresenter.java
- app/src/main/java/org/akvo/flow/presentation/datapoints/map/DataPointsMapPresenter.java
- app/src/main/java/org/akvo/flow/service/DataPointUploadService.java
- data/src/main/java/org/akvo/flow/data/datasource/DatabaseDataSource.java
- data/src/main/java/org/akvo/flow/data/entity/FilesResultMapper.java
- data/src/main/java/org/akvo/flow/data/entity/FilteredFilesResult.java
- data/src/main/java/org/akvo/flow/data/entity/FormIdMapper.java
- data/src/main/java/org/akvo/flow/data/entity/SurveyInstanceIdMapper.java
- data/src/main/java/org/akvo/flow/data/repository/MissingAndDeletedDataRepository.java
- data/src/main/java/org/akvo/flow/data/repository/SurveyDataRepository.java
- data/src/test/java/org/akvo/flow/data/entity/FilesResultMapperTest.java
- database/src/main/java/org/akvo/flow/database/britedb/BriteSurveyDbAdapter.java
- domain/src/main/java/org/akvo/flow/domain/interactor/AllDeviceNotifications.java
- domain/src/main/java/org/akvo/flow/domain/interactor/SurveyDeviceNotifications.java
- domain/src/main/java/org/akvo/flow/domain/repository/MissingAndDeletedRepository.java
- domain/src/main/java/org/akvo/flow/domain/repository/SurveyRepository.java
Before adding tests, I had to extract the logic of getting missing and deleted files to allow easier testing
Extract missing and deleted related methods to another repository
NA
> [#1297] refactor missing and deleted logic (connect #1297)

- app/src/main/java/org/akvo/flow/ui/view/media/photo/PhotoQuestionView.java
- data/src/main/java/org/akvo/flow/data/datasource/ImageDataSource.java
- data/src/main/java/org/akvo/flow/data/repository/FileDataRepository.java
- data/src/test/java/org/akvo/flow/data/repository/FileDataRepositoryTest.java
- domain/src/main/java/org/akvo/flow/domain/interactor/SaveResizedImage.java
We have noticed some missing images
Make sure to not allow submitting if no valid image
Add tests to image saving/resizing logic
NA
> Issue/1304 image tests (connect #1304)

- .gitignore
- data/src/main/java/org/akvo/flow/data/datasource/FlowFileBrowser.java
- data/src/main/java/org/akvo/flow/data/entity/S3FileMapper.java
- data/src/main/java/org/akvo/flow/data/entity/TransmissionMapper.java
- data/src/test/java/org/akvo/flow/data/entity/S3FileMapperTest.java
- data/src/test/java/org/akvo/flow/data/entity/TransmissionMapperTest.java
- data/src/test/java/org/akvo/flow/data/repository/SurveyDataRepositoryTest.java
Data syncing logic needs to be tested
Part 3: added tests to mappers and getSurveyTransmissions method
NA
> Issue/1297 part3 (connect #1297)

- app/src/main/java/org/akvo/flow/injector/module/ApplicationModule.java
- data/build.gradle
- data/src/main/java/org/akvo/flow/data/net/BodyCreator.java
- data/src/main/java/org/akvo/flow/data/net/RestApi.java
- data/src/main/java/org/akvo/flow/data/net/s3/BodyCreator.java
- data/src/main/java/org/akvo/flow/data/repository/SurveyDataRepository.java
- data/src/test/java/org/akvo/flow/data/repository/MissingAndDeletedDataRepositoryTest.java
- data/src/test/java/org/akvo/flow/data/repository/SurveyDataRepositoryTest.java
need to add tests to data syncing
final part 4: adding tests to sync transmission
NA
> Issue/1297 part4 (connect #1297)

- data/src/main/java/org/akvo/flow/data/datasource/DatabaseDataSource.java
The call to update errored surveyInstances was in the wrong place so the same code was executed too many times
fixed the error
NA
> [#1310] the same methods were called multiple times

- app/src/androidTest/java/org/akvo/flow/activity/form/FormActivityTestUtil.java
- app/src/androidTest/java/org/akvo/flow/activity/form/formfill/PhotoQuestionDependentViewTest.java
- app/src/androidTest/java/org/akvo/flow/activity/form/formfill/PhotoQuestionMandatoryViewTest.java
- app/src/androidTest/java/org/akvo/flow/activity/form/formfill/PhotoQuestionNonMandatoryViewTest.java
- app/src/androidTest/res/raw/photo_form.xml
- app/src/androidTest/res/raw/photo_form_dependent.xml
- app/src/androidTest/res/raw/photo_form_mandatory.xml
no tests for image submissions
added a few tests to make sure one can submit without image (non mandatory) or cannot if mandatory
as per issue #1320 
NA
> Ui tests for photo questions (connect #1320)

- app/src/main/java/org/akvo/flow/ui/view/CascadeQuestionView.java
- app/src/main/java/org/akvo/flow/ui/view/DateQuestionView.java
- app/src/main/java/org/akvo/flow/ui/view/FreetextQuestionView.java
- app/src/main/java/org/akvo/flow/ui/view/GeoshapeQuestionView.java
- app/src/main/java/org/akvo/flow/ui/view/QuestionView.java
- app/src/main/java/org/akvo/flow/ui/view/barcode/BarcodeQuestionViewMultiple.java
- app/src/main/java/org/akvo/flow/ui/view/barcode/BarcodeQuestionViewSingle.java
- app/src/main/java/org/akvo/flow/ui/view/geolocation/GeoQuestionView.java
- app/src/main/java/org/akvo/flow/ui/view/option/OptionQuestionView.java
- app/src/main/java/org/akvo/flow/ui/view/signature/SignatureQuestionView.java
Most question types repetitions do not get deleted
Make sure we save properly the repetitions with their iterations
NA
> Issue/1294 repetitions delete (connect #1294)

- data/src/main/java/org/akvo/flow/data/datasource/DatabaseDataSource.java
- data/src/main/java/org/akvo/flow/data/entity/form/Form.java
- data/src/main/java/org/akvo/flow/data/entity/form/FormHeaderParser.java
- data/src/main/java/org/akvo/flow/data/entity/form/FormIdMapper.java
- data/src/main/java/org/akvo/flow/data/entity/form/XmlFormParser.java
- data/src/main/java/org/akvo/flow/data/repository/FormDataRepository.java
- data/src/main/java/org/akvo/flow/data/repository/SurveyDataRepository.java
- data/src/test/java/org/akvo/flow/data/entity/FormHeaderParserTest.java
- data/src/test/java/org/akvo/flow/data/entity/FormIdMapperTest.java
- data/src/test/java/org/akvo/flow/data/repository/FormDataRepositoryTest.java
- data/src/test/java/org/akvo/flow/data/repository/SurveyDataRepositoryTest.java
Form version displayed and saved with the answers is the one from the backend
Use the form version from the form xml file
NA
> Issue/1324 form version fix (connect #1324)

- app/src/main/java/org/akvo/flow/ui/view/CaddisflyQuestionView.java
- domain/src/main/java/org/akvo/flow/domain/interactor/CopyFile.java
Error when trying to copy the whole caddisfly folder instead of the expected image
Ignore the folder
NA
> [#1293] fixes only expect caddisfly images, not folders (connect #1293)

- app/src/main/java/org/akvo/flow/activity/FormActivity.java
- app/src/main/java/org/akvo/flow/domain/Question.java
- app/src/main/java/org/akvo/flow/event/QuestionInteractionEvent.java
- app/src/main/java/org/akvo/flow/serialization/form/SurveyHandler.java
- app/src/main/java/org/akvo/flow/ui/Navigator.java
- app/src/main/java/org/akvo/flow/ui/view/FreetextQuestionView.java
- app/src/main/java/org/akvo/flow/util/ConstantUtil.java
- app/src/main/res/layout/freetext_question_view.xml
- app/src/main/res/values/strings.xml
old caddisfly implementation still displayed but the question cannot be answered
remove the old caddisfly implementation, text question can only be text
NA
> [#1335] Removed old caddisfly implementation (connect #1335)

- app/src/main/res/values-es/strings.xml
- app/src/main/res/values-fr/strings.xml
- app/src/main/res/values-hi/strings.xml
- app/src/main/res/values-in/strings.xml
- app/src/main/res/values-km/strings.xml
- app/src/main/res/values-ne/strings.xml
- app/src/main/res/values-nl/strings.xml
- app/src/main/res/values-pt/strings.xml
- app/src/main/res/values-vi/strings.xml
Missing translations
Translated and pulled for French, Portuguese and Spanish. The other languages were only updated for the deleted strings
NA
> [#1307] pulled latest translations (connect #1307)

- app/src/main/java/org/akvo/flow/ui/Navigator.java
Issue with some samsung devices that are unable to take picture
Remove the check
NA
> [#1350] remove check, resolve activity should return false if no camera (connect #1350)

- data/src/main/java/org/akvo/flow/data/datasource/files/FileDataSource.java
Lots of errors related to unexpected folder found when moving collected data from private to public folders
remove the unexpected folder
NA
> [#1352] remove the unexpected folder (connect #1352)

- data/src/main/java/org/akvo/flow/data/datasource/preferences/SharedPreferencesDataSource.java
- data/src/main/java/org/akvo/flow/data/repository/UserDataRepository.java
- domain/src/main/java/org/akvo/flow/domain/entity/OfflineArea.java
- domain/src/main/java/org/akvo/flow/domain/entity/OfflineBounds.java
- domain/src/main/java/org/akvo/flow/domain/interactor/offline/GetSelectedOfflineArea.java
- domain/src/main/java/org/akvo/flow/domain/interactor/offline/SaveSelectedOfflineArea.java
- domain/src/main/java/org/akvo/flow/domain/repository/UserRepository.java
NA
offline area selection for usage data and domain classes
NA
> [#1341] part1: data and domain classes to select offline area

- app/src/main/java/org/akvo/flow/presentation/datapoints/map/offline/OfflineAreasAdapter.java
- app/src/main/java/org/akvo/flow/presentation/datapoints/map/offline/OfflineMapSelectedListener.java
- app/src/main/java/org/akvo/flow/presentation/datapoints/map/offline/OfflineMapsView.java
NA
part 3 of the #1341 is to add offline areas adapter (to display them) and listeners
NA
> [#1341] offline adapter and listeners

- app/google-services.json
NA
Securing the firebase key, a new config file has been created
NA
> [#1408] firebase config file update

- app/src/main/java/org/akvo/flow/ui/view/geolocation/GeoQuestionView.java
Non mandatory geo question cannot be submitted if empty
Allow submitting form when a geoquestion is not mandatory
NA
> [#1405] non mandatory geo questions can now be submitted

- .gitignore
- app/build.gradle
- app/src/main/java/org/akvo/flow/app/FlowApp.java
- app/src/main/java/org/akvo/flow/util/Base32.java
- app/src/main/java/org/akvo/flow/util/PlatformUtil.java
- app/src/test/java/org/akvo/flow/util/Base32Test.kt
- build.gradle
some record uids are shorter because the original uuid started with 0 or 00
The same as https://github.com/akvo/akvo-flow/blob/develop/GAE/src/com/gallatinsystems/surveyal/domain/SurveyedLocale.java#L260
Added some tests to make sure it works
NA
> [#1411] fixes issue with shorter record uuids

- app/src/main/java/org/akvo/flow/presentation/signature/SignatureActivity.java
- app/src/main/java/org/akvo/flow/ui/view/signature/SignatureQuestionView.java
- app/src/main/java/org/akvo/flow/util/image/GlideImageLoader.java
- app/src/main/java/org/akvo/flow/util/image/ImageLoader.java
> [#1446] fix the issue where the signature was not properly loaded

- uicomponents/src/main/res/values/strings.xml
> [#1343] fixed walkthrough string

- app/src/main/AndroidManifest.xml
- app/src/main/java/org/akvo/flow/activity/BackActivity.java
- app/src/main/java/org/akvo/flow/activity/FormActivity.java
- app/src/main/java/org/akvo/flow/activity/GeoshapeActivity.java
- app/src/main/java/org/akvo/flow/injector/component/ViewComponent.java
- app/src/main/java/org/akvo/flow/presentation/geoshape/ViewGeoShapeActivity.java
- app/src/main/java/org/akvo/flow/ui/Navigator.java
- app/src/main/java/org/akvo/flow/ui/view/GeoshapeQuestionView.java
- app/src/main/res/layout/activity_view_geo_shape.xml
- app/src/main/res/layout/content_view_geo_shape.xml
- app/src/main/res/menu/view_geoshape_activity.xml
NA
Use mapbox to view read only geoshpapes
> [#1462] basic view of existing geoshape

- offlinemaps/src/main/java/org/akvo/flow/offlinemaps/di/OfflineFeatureComponent.java
- offlinemaps/src/main/java/org/akvo/flow/offlinemaps/presentation/geoshapes/GeoShapesMapViewImpl.java
NA
Part 2 of moving geoshapes to use mapbox: add the class that is responsible for drawing the map and the shapes
NA
> [#1447] added geoshape mapbox MapView

- build.gradle
- offlinemaps/src/main/java/org/akvo/flow/offlinemaps/data/DataRegionRepository.java
- offlinemaps/src/main/java/org/akvo/flow/offlinemaps/presentation/list/OfflineAreasListPresenter.java
There seems to be a crash when deleting an already selected area
The fix was done on the library, here we update the library version and make sure to delete the selected area if it has been deleted
NA
> [#1468] Fix crash when deleting selected area

- app/src/main/java/org/akvo/flow/presentation/geoshape/entities/AreaShape.java
- app/src/main/java/org/akvo/flow/presentation/geoshape/entities/LineShape.java
- app/src/main/java/org/akvo/flow/presentation/geoshape/entities/PointShape.java
- app/src/main/java/org/akvo/flow/presentation/geoshape/entities/Shape.java
- app/src/main/java/org/akvo/flow/presentation/geoshape/entities/ShapePoint.java
NA
part 3 of the solution https://github.com/akvo/akvo-flow-mobile/pull/1471
Added shape related classes
NA
> [#1447] create geoshapes mapbox part 3

- app/src/main/java/org/akvo/flow/injector/component/ViewComponent.java
- app/src/main/java/org/akvo/flow/presentation/geoshape/entities/CoordinatesMapper.java
- app/src/main/java/org/akvo/flow/presentation/geoshape/properties/AreaCounter.java
- app/src/main/java/org/akvo/flow/presentation/geoshape/properties/LengthCounter.java
- app/src/main/java/org/akvo/flow/presentation/geoshape/properties/PropertiesDialog.java
- app/src/main/java/org/akvo/flow/presentation/geoshape/properties/PropertiesPresenter.java
- app/src/main/java/org/akvo/flow/presentation/geoshape/properties/PropertiesView.java
NA
part 4 of creating geoshapes:
Display properties dialog showing number of points, length and area + added coordinates mapper
> [#1447] added properties dialog

- app/build.gradle
- app/src/main/java/org/akvo/flow/app/FlowApp.java
- build.gradle
- data/src/main/java/org/akvo/flow/data/net/ErrorLoggerFunction.kt
- data/src/main/java/org/akvo/flow/data/net/RestApi.java
- data/src/main/java/org/akvo/flow/data/repository/FormDataRepository.java
There seems to be an error with assigned forms
make the error logging clearer where the issue happens
NA
> [#1512] improve logging of networking errors

- app/src/main/java/org/akvo/flow/activity/SurveyActivity.java
- app/src/main/java/org/akvo/flow/presentation/main/MainActivity.java
- app/src/main/java/org/akvo/flow/presentation/survey/SurveyPresenter.java
- app/src/main/java/org/akvo/flow/presentation/survey/SurveyView.java
- app/src/main/java/org/akvo/flow/ui/Navigator.java
- build.gradle
- gradle.properties
- gradle/wrapper/gradle-wrapper.properties
walkthrough is only show to users who have just downloaded the app, not ones that update it.
show walkthrough for those who update the app and have not se…
> [#1597] Improved walkthrough logic

- app/src/main/java/org/akvo/flow/activity/SurveyActivity.java
- app/src/main/java/org/akvo/flow/presentation/main/MainActivity.java
- app/src/main/java/org/akvo/flow/presentation/survey/SurveyPresenter.java
- app/src/main/java/org/akvo/flow/presentation/survey/SurveyView.java
- app/src/main/java/org/akvo/flow/ui/Navigator.java
NA
realized the changes introduced in https://github.com/akvo/akvo-flow-mobile/pull/1610 are not necessary and walkthourgh already works as expected
NA
> [#1597] reverting changes related to walkthrough

- .gitignore
- uicomponents/src/main/res/values-es/strings.xml
- uicomponents/src/main/res/values-fr/strings.xml
- uicomponents/src/main/res/values-hi/strings.xml
- uicomponents/src/main/res/values-in/strings.xml
- uicomponents/src/main/res/values-km/strings.xml
- uicomponents/src/main/res/values-ne/strings.xml
- uicomponents/src/main/res/values-pt/strings.xml
- uicomponents/src/main/res/values-vi/strings.xml
NA
Pull latest translations from transifex:
* deleted strings are automatically removed from all languages
* new translations only for French and Spanish
NA
> [#1626] pull latest translations

- build.gradle
Crash when using geoshapes
Update mapbox SDK
NA
> [#1632] update mapbox to latest version

- app/src/main/java/org/akvo/flow/presentation/geoshape/create/CreateGeoShapeActivity.java
- app/src/main/java/org/akvo/flow/presentation/geoshape/create/CreateGeoShapePresenter.java
- app/src/main/java/org/akvo/flow/presentation/geoshape/entities/FeatureMapper.java
- offlinemaps/src/main/java/org/akvo/flow/offlinemaps/presentation/geoshapes/GeoShapesMapViewImpl.java
One can only select shape points
allow selection of whole shape
NA
> [#1640] allow selecting whole shape, not just point

- app/src/main/java/org/akvo/flow/presentation/geoshape/create/CreateGeoShapePresenter.java
- offlinemaps/src/main/java/org/akvo/flow/offlinemaps/presentation/geoshapes/GeoShapesMapViewImpl.java
NA
When switching map styles, the annotations were not properly reset, make sure to clear old points and reinitialize them
NA
> [#1655] make sure old selected points are cleared

- offlinemaps/src/main/res/drawable/ic_add_map_icon.xml
- offlinemaps/src/main/res/layout/activity_offline_area_list.xml
NA
New icon for adding offline maps:
NA
> [#1663] new icon for add new map FAB

- build.gradle
NA
In order to update some of the Android libraries and tools, we need to drop support for Android Api 15
NA
> [#1658] increase minimum api to 16

- data/src/main/java/org/akvo/flow/data/net/RestServiceFactory.java
NA
After refactoring the datapoint download logic, this rx call adapter remained, so needs to be removed
NA
> [#1688] remove rx adapter from non rx method

- SECURITY.md
- security.txt
No security policy file
Add security policy
NA
> Create security policy files

- app/src/androidTest/java/org/akvo/flow/activity/form/formfill/LockedGeoQuestionViewTest.kt
- app/src/androidTest/java/org/akvo/flow/presentation/ScreenRobot.kt
- app/src/androidTest/java/org/akvo/flow/presentation/about/AboutActivityTest.kt
- app/src/androidTest/java/org/akvo/flow/presentation/help/HelpActivityTest.kt
- app/src/androidTest/java/org/akvo/flow/presentation/record/RecordActivityTest.kt
- app/src/androidTest/java/org/akvo/flow/presentation/settings/PreferenceActivityTest.kt
> Added more basic UI tests

- app/src/main/java/org/akvo/flow/service/FileChangeTrackingWorker.java
Fix a crash related to a null context
> [#1701] fix crash

- data/src/main/java/org/akvo/flow/data/repository/DataPointDataRepository.kt
- domain/src/main/java/org/akvo/flow/domain/interactor/DownloadDataPoints.kt
datapoint download fails even if only image download fails
datapoints download should continue if images download fails
* catch image download errors
* log datapoint download errors
> [#1705] fix datapoint download error

- app/src/main/java/org/akvo/flow/event/PermissionAwareLocationListener.java
- app/src/main/java/org/akvo/flow/ui/view/CaddisflyQuestionView.java
- app/src/main/java/org/akvo/flow/ui/view/QuestionView.java
- app/src/main/java/org/akvo/flow/ui/view/geolocation/GeoQuestionView.java
- app/src/main/java/org/akvo/flow/ui/view/media/photo/PhotoQuestionView.java
- app/src/main/java/org/akvo/flow/ui/view/media/video/VideoQuestionView.java
- app/src/main/java/org/akvo/flow/util/AppPermissionsHelper.java
- app/src/main/java/org/akvo/flow/util/StoragePermissionsHelper.java
Crash in some cases when permissions array returns empty
Check if array is empty
NA
> [#1717] make sure permissions list is not empty to avoid crash

- app/src/main/java/org/akvo/flow/activity/SurveyActivity.java
- app/src/main/java/org/akvo/flow/data/database/SurveyDbDataSource.java
- data/src/main/java/org/akvo/flow/data/datasource/DatabaseDataSource.java
- data/src/main/java/org/akvo/flow/data/repository/SurveyDataRepository.java
- database/src/main/java/org/akvo/flow/database/DatabaseHelper.java
- database/src/main/java/org/akvo/flow/database/SurveyDbAdapter.java
- database/src/main/java/org/akvo/flow/database/britedb/BriteSurveyDbAdapter.java
- database/src/main/java/org/akvo/flow/database/upgrade/SurveyViewedUpgrader.kt
- database/src/main/java/org/akvo/flow/database/upgrade/UpgraderFactory.java
- database/src/test/java/org/akvo/flow/database/upgrade/UpgraderFactoryTest.java
- domain/src/main/java/org/akvo/flow/domain/interactor/datapoints/GetSavedDataPoints.java
- domain/src/main/java/org/akvo/flow/domain/repository/SurveyRepository.java
> [#1733] Stop deleting empty datapoints

- database/src/main/res/values/languages.xml
> [#1766] added Sidaama

- app/src/main/java/org/akvo/flow/service/bootstrap/BootstrapProcessor.kt
change required after https://github.com/akvo/akvo-flow-server-config/commit/9248d9ff4977a92f2d5fea3a39f5adf182b9beaf
example of bootstrap form:
`<survey name="New form" defaultLanguageCode="en" version="1.0" app="akvoflow-uat2" surveyGroupId="343410001" surveyGroupName="TranslationsSidaama" surveyId="321730103">`
> [#1768] fix bootstrap issue after changes in config files

- app/src/main/java/org/akvo/flow/injector/module/ViewModule.java
- app/src/main/java/org/akvo/flow/presentation/form/caddisfly/CaddisflyPresenter.java
- app/src/main/java/org/akvo/flow/ui/view/CaddisflyQuestionView.java
- app/src/main/java/org/akvo/flow/util/ConstantUtil.java
- data/src/main/java/org/akvo/flow/data/datasource/files/FileDataSource.java
- data/src/main/java/org/akvo/flow/data/repository/FileDataRepository.java
- data/src/main/java/org/akvo/flow/data/util/FileHelper.java
- domain/src/main/java/org/akvo/flow/domain/interactor/SaveByteArrayToFile.java
- domain/src/main/java/org/akvo/flow/domain/repository/FileRepository.java
#1882 - Flow cannot access Caddisfly images in external folder
Receive image from Caddisfly as byte array
> Issue/1882 Method for receiving Caddisfly images
