app/src/main/java/org/akvo/flow/domain/Question.java

copies caddisfly test uuid to the question object.
The thing to check is if caddisfly questions work in repeated question groups.
In flowglimmerofhope instance, use surveyid 50234000 (1.9.10 caddisfly test). Check if question 2 ("test chlorine") in the tab "Few C. tests with photos repeated" works.

[#462] copy CaddisflyRes property in repeated question groups

---

app/src/main/java/org/akvo/flow/activity/AddUserActivity.java
app/src/main/res/layout/add_user_activity.xml

Keyboard covers the next button so user has no way to "send" the data he just input unless he presses back button to hide the keyboard. 
Use actionDone provided by Android so from the keyboard you press the "done" or a tick button which will act the same way as if the next button was pressed
On a device without any users logged you will get the user creation screen.
- Create user and use the keyboard only to navigate from first text input to the next and the tick or save (depends on keyboards you may see either a "done" or just an image with a tick.
- Make sure the user is created correctly
Restart the same procedure but using the old next button (should still work the same way as before).

Improvement when keyboard covers the next button when creating user (connect #469)

---

app/build.gradle
app/src/main/java/org/akvo/flow/service/BootstrapService.java
app/src/main/java/org/akvo/flow/util/ConstantUtil.java

The survey name xml file was overwritten due to the fact that 2 or more survey forms had the same name.
Have included the folder name (survey id) as a file path for the form xml file to make sure the survey xml file is unique.
Also included new android annotations librabry:
https://developer.android.com/studio/write/annotations.html
This allows you to add annotations such as @Nullable and @NonNull or @StringRes and then run Inspect code and that way avoid bugs and crashes.
Test Plan:
Test manual importing surveys using the zipfiles especially with surveys that have same form names.

Same name survey manual import fail (connect #476)

---

app/src/main/java/org/akvo/flow/activity/SurveyActivity.java

Logged in as xxx is shown every time the user rotates the screen. This is not useful.
stop calling displaySelectedUser() in onCreate
NA

Stop showing "logged in as " all the time the activity is created (connect #498)

---

app/src/main/java/org/akvo/flow/dao/DataProvider.java

If you wanted to search a datapoint the search was made starting at the beginning of the word.
A name like 'Barcelona - 50' would never be found if you search by '50'.
Made it possible to search for the name anywhere even if the name is composed of multiple items.
…inning

Allow searching any place for the datapoint name (connect #467)

---

app/src/main/res/values/strings.xml

There was a crash due to the string formatter expecting a number while we provided a string
Specified we expect a string arg
NA

Fixed crash in About dialog (connect #545)

---

util/ide/android-studio/Akvo Java Source Formatting.xml

No code formatting for Android studio. Eclipse formatting file from 2 years ago.
Imported the code formatting file from akvo-flow repo. We still need to define some Android specific formatting and XML but at least the java code style is consistent between akvo-flow and akvo-flow-mobile
NA
No issue created
No test plan since there is nothing to test, this does not affect the app code

Imported Akvo Flow eclipse settings into android studio

---

app/src/main/java/org/akvo/flow/activity/RecordActivity.java
app/src/main/java/org/akvo/flow/ui/fragment/FormListFragment.java
app/src/main/res/layout/survey_item.xml
app/src/main/res/values/dimens.xml

Form name was not bieng wrapped in some cases due to the fact that 2 diferent textviews were being used and if the first one was too large, the second one was displayed in a strange way (see screenshots on the issue)
Use spannable and only one TextView to prevent that issue. Spannable allows to have diferent text sizes within one textView for example.

Form name wrap issue (connect #521)

---

app/src/main/java/org/akvo/flow/ui/view/CascadeQuestionView.java
app/src/main/res/layout/cascade_spinner_item.xml
app/src/main/res/layout/cascading_level_item.xml
app/src/main/res/values/dimens.xml

When cascades had a too long name, only the first line was shown
Make cascade layout use a custom layout to display all the cascade item text
The styling will be fixed with the issue #559

Cascade long text wrap (connect #568)

---

app/src/main/java/org/akvo/flow/app/FlowApp.java
app/src/main/java/org/akvo/flow/service/ApkUpdateService.java
app/src/main/java/org/akvo/flow/util/ConstantUtil.java

There was an issue and the dialog was not being displayed in the first 24hours. The reason for that is that I think is since the task is scheduled within 24 hours, if in the meantime the app is restart, the task is rescheduled for another 24hours.
The fist task will run within 1 minute and then consecutive runs will be every 24 hours. If the app is restarted, the task will run immediately.

Fixed dialog was not being displayed in the first 24 hours (connect #578)

---

app/src/main/java/org/akvo/flow/activity/GeoshapeActivity.java
app/src/main/res/drawable/image_button_background.xml
app/src/main/res/drawable/image_button_disabled.xml
app/src/main/res/drawable/image_button_normal.xml
app/src/main/res/drawable/image_button_selected.xml
app/src/main/res/layout/geoshape_activity.xml
app/src/main/res/values/colors.xml
app/src/main/res/values/styles.xml

The geoshape bottom image buttons started to look disabled after support library update
created new background and styling for the image buttons
In the screenshot, you can see that the 3rd button is disabled which is normal.

Fixing the geoshape image button styling (connect #597)

---

app/src/main/java/org/akvo/flow/service/DataSyncService.java
app/src/main/java/org/akvo/flow/util/ConstantUtil.java
app/src/main/java/org/akvo/flow/util/NotificationHelper.java

Too many notifications are displayed
Remove notification when data sync after creating survey. Only error notifications will be shown.
NA

Removed notifications for Data sync when no errors (connect #584)

---

app/src/main/java/org/akvo/flow/ui/Navigator.java
app/src/main/java/org/akvo/flow/ui/fragment/GpsDisabledDialogFragment.java
app/src/main/java/org/akvo/flow/ui/view/GeoQuestionView.java
app/src/main/java/org/akvo/flow/util/ViewUtil.java

There is a crash when we attempt to add a dialog and the activity is being destroyed (due to device rotation).
The solution is to use DialogFragments instead which handle better activity lifecycle
NA

Fixed BadTokenException when display Gps disabled Dialog (connect #656)

---

app/src/main/java/org/akvo/flow/ui/view/DateQuestionView.java

The date was displayed correctly in the picker but once saved to database then it was displayed incorrectly in timezones which are far away from GMT.
Making sure to use time stamp and set calendar with time stamp without using Date.
NA

Fix date picker wrong formatting (connect #662)

---

app/build.gradle
app/src/androidTest/java/org/akvo/flow/ui/view/CaddisflyQuestionViewTest.java
app/src/main/java/org/akvo/flow/ui/adapter/CaddisflyResultsAdapter.java
app/src/main/java/org/akvo/flow/ui/model/caddisfly/CaddisflyJsonMapper.java
app/src/main/java/org/akvo/flow/ui/model/caddisfly/CaddisflyResult.java
app/src/main/java/org/akvo/flow/ui/model/caddisfly/CaddisflyTestResult.java
app/src/main/java/org/akvo/flow/ui/view/CaddisflyQuestionView.java
app/src/main/res/layout/caddisfly_question_view.xml
app/src/main/res/layout/caddisfly_question_view_result_item.xml
app/src/main/res/values/strings.xml

Caddisfly responses are not displayed. Only "test captured successfully" is displayed
Displaying captured results by parsing the json string.

Displaying caddisfly results in detail (connect #470)

---

app/src/main/java/org/akvo/flow/ui/Navigator.java
app/src/main/java/org/akvo/flow/ui/fragment/GpsDisabledDialogFragment.java
app/src/main/res/values/strings.xml

When gps is disabled we display a dialog to prompt user to go to location setting and enable location. That dialog had e very long and complicated text.
Simplify the text.
Extra bonus added check if that intent exists and if it does not, just take the user to general settings screen.

Location setting dialog message (connect #672)

---

app/src/main/java/org/akvo/flow/ui/view/GeoInputContainer.java

GeoQuestionView: manual input is still possible while waiting for device location
disabling edit texts when we start getting automatic location, re-enabling if cancelled/timeout/completed
NA

Disabling manual input fields while getting automatic location

---

app/src/main/java/org/akvo/flow/ui/view/GeoInputContainer.java

Input values were being checked even if fields was empty which displayed an error message that did not make sense (when we were waiting for a device location)
If fields are empty no need to check if the value is valid or not
NA

Removed check when manual input location fields are empty (connect #679)

---

app/src/main/java/org/akvo/flow/activity/FormActivity.java
app/src/main/java/org/akvo/flow/activity/RecordActivity.java
app/src/main/java/org/akvo/flow/data/database/SurveyDbAdapter.java
app/src/main/java/org/akvo/flow/data/loader/SurveyInstanceLoader.java
app/src/main/java/org/akvo/flow/data/loader/SurveyInstanceResponseLoader.java
app/src/main/java/org/akvo/flow/ui/adapter/ResponseListAdapter.java
app/src/main/java/org/akvo/flow/ui/fragment/ResponseListFragment.java

Clearing the answers but the entry was still being displayed in the list when pressing "back"
Only display response entries which have actual answers and update the activity title to "unknown datapoint" when the named record has been deleted.
NA

Record activity still shows deleted entry (connect #742)

---

app/src/main/java/org/akvo/flow/data/database/SurveyDbAdapter.java

When you synced a datapoint created on that same device, the transmission data entry was duplicated.
check if a transmission exists first and update.
NA

If a transmission entry already exists, just update its date (connect #737)

---

app/src/main/java/org/akvo/flow/activity/SurveyActivity.java
app/src/main/java/org/akvo/flow/app/FlowApp.java
app/src/main/java/org/akvo/flow/data/DataProvider.java
app/src/main/java/org/akvo/flow/ui/fragment/DatapointsFragment.java
app/src/main/java/org/akvo/flow/ui/fragment/DrawerFragment.java
app/src/main/java/org/akvo/flow/ui/fragment/MapFragment.java
app/src/main/java/org/akvo/flow/ui/fragment/SurveyedLocaleListFragment.java

After rotating the device, the wrong survey is shown
Make sure the correct survey is displayed then device is rotated
NA

Prevent survey group from being reset after device rotation (connect #767)

---

app/src/main/java/org/akvo/flow/ui/view/geolocation/GeoQuestionView.java

Hard to reproduce but what happens is the app is trying to close an already opened database. One of the hypothesis is the app has already gone through onDestroy method but at the same time a new location information comes from the listener. 
Stop location updates when activity is destroyed.
NA

Attempt to fix crash in FormActivity (connect #552)

---

app/src/main/java/org/akvo/flow/ui/view/geolocation/GeoQuestionView.java
app/src/main/res/layout/form_activity.xml
app/src/main/res/values-land/dimens.xml

The crash is due tot he fact that the system is attempting to add the snackbar to a ScrollView (not sure why). The ScrollView cannot have more than one child so the app crashes.
Passing the id of the CoordinatorLayout to snackbar directly.
+ set snackbar text color to white (was black on dark background so invisible on some devices)
NA

Fixed crash related to snackbar (connect #743)

---

app/src/main/java/org/akvo/flow/ui/view/ErrorMessageFormatter.java
app/src/main/java/org/akvo/flow/ui/view/FreetextQuestionView.java
app/src/main/java/org/akvo/flow/ui/view/QuestionView.java
app/src/main/java/org/akvo/flow/ui/view/geolocation/GeoInputContainer.java

On android 2.3 the error message was white on white background -> invisible 
On latest android versions the error message is white text on black background
Using spannable to set the error message text color to RED so it will be visible on both white and black backgrounds

Fixed styling of error messages (connect #750)

---

app/src/main/java/org/akvo/flow/async/ClearDataAsyncTask.java

When pressed delete all collected data we were also deleting the user which is a mistake
Only delete user preferences when "delete everything" is selected
NA

Fixed user preferences deleted even when not needed (connect #790)

---

app/src/main/java/org/akvo/flow/ui/view/QuestionGroupTab.java

When only one repetition, the whole repeated group was not displayed
Making sure repeated groups answers are found correctly with question ids in format 123456789 or 123456789|0
NA

Repeated group issue (connect #873)

---

app/src/main/java/org/akvo/flow/domain/QuestionResponse.java

Answers are not displayed correctly in the datapoint history
Fixed when non repeatable question groups answers are not found:
this was due to the responses key being in format 123456789|0
NA

Fix missing answers in datapoint history (connect #899)

---

app/build.gradle
util/upload-apk/script/flow-releases.sh

deploy script no longer works due to full path filename no longer working the same way in gradle 4.1
updating the apk location path and file naming
NA

Fixed build script (connect #932)

---

app/src/main/res/layout/activity_full_image.xml

Images when displayed in full screen mode, were cut off
Display images in full screen correctly both in portrait and landscape

Full screen images (connect #989)

---

app/build.gradle
build.gradle

We do not check apps method counts and it is easy to be surprised and reach the 65k limit
added a tool to count methods after each build and display results in command line. Example:
after running `./gradlew aFD`
**> Task :app:countFlowDebugDexMethods
Total methods in flow.apk: 56203 (85.76% used)
Total fields in flow.apk:  30862 (47.09% used)
Total classes in flow.apk:  7034 (10.73% used)
Methods remaining in flow.apk: 9332
Fields remaining in flow.apk:  34673
Classes remaining in flow.apk:  58501**

Added dexcount tool to always be aware of methods number (connect #1082)

---

app/src/main/java/org/akvo/flow/app/FlowApp.java
app/src/main/java/org/akvo/flow/injector/component/ApplicationComponent.java
app/src/main/java/org/akvo/flow/injector/module/ApplicationModule.java
app/src/main/java/org/akvo/flow/injector/module/ViewModule.java
data/src/main/java/org/akvo/flow/data/datasource/DataSourceFactory.java
data/src/main/java/org/akvo/flow/data/datasource/preferences/SecureSharedPreferencesDataSource.java
data/src/main/java/org/akvo/flow/data/datasource/preferences/SharedPreferencesDataSource.java
data/src/main/java/org/akvo/flow/data/repository/SetupDataRepository.java
domain/src/main/java/org/akvo/flow/domain/interactor/setup/SaveSetup.java
domain/src/main/java/org/akvo/flow/domain/interactor/setup/SetUpParams.java
domain/src/main/java/org/akvo/flow/domain/repository/SetupRepository.java

The configuration settings for each dashboard are generated at build time.
see https://github.com/akvo/akvo-flow-mobile/blob/develop/app/build.gradle#L106
If we want to publish a single app for all it will be impossible to get those after we update.
Save each setup string as encoded preference.
We save only once, if there is already a value it will not be overridden.
keys and values are encoded so if someone tries to read the shared preferences, he will not know exactly what they are. This is not super secure but better than have them just in plain sight.
NA

Save build config (connect #1092)

---

app/src/main/java/org/akvo/flow/presentation/settings/DownloadFormDialog.java
app/src/main/java/org/akvo/flow/presentation/settings/PreferenceActivity.java
app/src/main/res/layout/download_form_dialog.xml
app/src/main/res/values/strings.xml

Download form and reload all forms logic was mixed up. Download form dialog had ugly margins
Fix the mixup and add margins to the dialog input via using a layout file
NA

Fixed mixed up download form and reload all forms (connect #1108)

---

app/src/main/java/org/akvo/flow/broadcast/BootReceiver.java
domain/src/main/java/org/akvo/flow/domain/interactor/UnPublishData.java

When device was reboot, the published files were deleted but the timer displayed in the ui was not reset
The alarm received a time in minutes instead of ms.
NA

Fixed published files get deleted when device reboots (connect #1044)

---

domain/src/main/java/org/akvo/flow/domain/interactor/ClearResponses.java

When deleting collected data only, the timer was not reset for published data and was still displayed when we came back to settings screen
clear the timer when collected data is removed
NA

When deleting responses only, reset the publish timer (connect #1058)

---

.gitignore
app/src/main/java/org/akvo/flow/activity/TransmissionHistoryActivity.java
app/src/main/java/org/akvo/flow/data/database/SurveyDbDataSource.java
app/src/main/java/org/akvo/flow/data/database/TransmissionsMapper.java
app/src/main/java/org/akvo/flow/service/DataSyncService.java
app/src/main/java/org/akvo/flow/util/files/ZipFileBrowser.java
data/src/main/java/org/akvo/flow/data/datasource/DatabaseDataSource.java
data/src/main/java/org/akvo/flow/data/datasource/FileDataSource.java
data/src/main/java/org/akvo/flow/data/entity/TransmissionFilenameMapper.java
data/src/main/java/org/akvo/flow/data/repository/FileDataRepository.java
data/src/main/java/org/akvo/flow/data/repository/SurveyDataRepository.java
database/src/main/java/org/akvo/flow/database/DatabaseHelper.java
database/src/main/java/org/akvo/flow/database/SurveyDbAdapter.java
database/src/main/java/org/akvo/flow/database/britedb/BriteSurveyDbAdapter.java
database/src/main/java/org/akvo/flow/database/migration/TransmissionMigrationHelper.java
database/src/main/java/org/akvo/flow/database/upgrade/ResponsesUpgrader.java
database/src/main/java/org/akvo/flow/database/upgrade/UpgraderFactory.java
database/src/test/java/org/akvo/flow/database/DatabaseHelperTest.java
database/src/test/java/org/akvo/flow/database/upgrade/UpgraderFactoryTest.java

Transmission contains absolute full path to media and zip files but this can lead to issues if the file has been moved, in applications with several users... 
We need to save only the file name and rebuild the path since we know where the files are placed. We also need to:
Migrate old transmissions to make sure they contain only filename
Make sure datasync logic uses the new path
Fix tests related to the database migration
When files are missing from the dashboard, we get their full paths, make sure to search only the filename in our database.
Stop updating transmissions after moving private files to public folder
NA

Fix transmission paths (connect #1084)

---

app/src/main/java/org/akvo/flow/service/DataSyncService.java

The full device file path is being sent to the backend when requesting file processing
Only send the filename
NA

Dataprocessing filepath fix (connect #1147)

---

app/src/main/java/org/akvo/flow/activity/TimeCheckActivity.java
app/src/main/java/org/akvo/flow/presentation/signature/SignatureActivity.java

on android 4.0 devices buttons from SignatureActivity and TimeActivity seemed disabled
make these activities to extedn appCompatActivity for correct theming
NA

Fixed buttons now shown correctly for android 4.0 devices (connect #1103)

---

app/src/main/java/org/akvo/flow/activity/GeoshapeActivity.java

User can press save and an empty shape is added to the survey 
We need to prevent saving of empty geoshapes
* save button is disabled if shape is empty
* when pressing save check shape is not empty
NA

[#745] prevent empty geoshapes from being saved (connect #745)

---

app/src/main/java/org/akvo/flow/ui/view/QuestionView.java
app/src/main/java/org/akvo/flow/ui/view/option/OptionQuestionViewMultiple.java
app/src/main/java/org/akvo/flow/ui/view/option/OptionQuestionViewSingle.java

options do not look nice when the text is longer than single line and it hard to know where the next option starts
add padding to help separate the options a bit and make it nicer for the user to chose the right option
NA

Add margin between each option of the question (connect #1225)

---

app/src/main/java/org/akvo/flow/activity/GeoshapeActivity.java

If user presses back after creating a shape, it gets lost.
When pressing back proceed the same way as with save.
NA

Issue/1199 geoshapes auto save (connect #1199)

---

app/src/main/res/layout/time_check_activity.xml
app/src/main/res/values/themes.xml

This is a crash that happens in the app current release and needs to be fixed. It is due to the usage of an old theme
using the new android theme, also removed useless nested layout and duplicated title.
NA

[#1229] Fixed crash in TimeCheckActivity (connect #1229)

---

app/src/main/AndroidManifest.xml
app/src/main/java/org/akvo/flow/ui/Navigator.java
build.gradle

Camera permission in the manifest + camera hardware -> duplicate
Since we use intents, camera permission is not needed.
Note: the tests will probably fail due to the other permissions not been handled.
NA

[#1232] remove CAMERA permission and make camera hardware not mandatory (connect #1232)

---

data/src/main/java/org/akvo/flow/data/entity/FormHeaderParser.java
data/src/main/java/org/akvo/flow/data/repository/FormDataRepository.java

Need to make some changes to all the background services in order to update to taget api 26.
Downloading forms has to be improved and refactored in order the logic to be sued either in a thread or a task.
This is only the first part of the data module changes.
This does not compile as some classes are missing but the PR would be too big other wise.
Final version: https://github.com/akvo/akvo-flow-mobile/pull/1269
NA

Issue/1267 data part1 (connect #1267)

---

app/src/main/java/org/akvo/flow/ui/view/media/photo/PhotoQuestionView.java

unable to submit even if photo question is not mandatory
fixes all photos are mandatory by checking valid file only if mandatory question
NA

[#1318] fix all photo questions seem to be mandatory

---

app/src/main/res/values/donottranslate.xml
app/src/main/res/values/strings.xml

NA
These 2 strings do not need to be translated as they serve to identify the channel and other apps do not translate them either. Only affects devices 8.0 ++
NA

[#1346] move 2 strings to non translatable ones

---

app/src/main/AndroidManifest.xml
app/src/main/java/org/akvo/flow/ui/Navigator.java
app/src/main/res/xml/file_paths.xml

crash when user tries to install app update
fix crash related to uri permission
NA

[#1355] fix crash related to uri permission on newest android devices (Connect #1355)

---

app/build.gradle
app/proguard-files/proguard-multidex-rules.pro

While working on migrating to jetpack, I have realised the ui tests do no work on android 4 but turns out they already did not work before that.
fix the tests on Android 4 (due to multidex)
NA

[#1368] fix tests on older android devices

---

util/upload-apk/src/main/java/org/akvo/flow/deploy/Deploy.java

S3 stopped liking http
store the URL in the datastore as https:

[#1379]Switch to https, since S3 no longer accepts http.

---

app/src/main/res/layout/fragment_map_box_map.xml
offlinemaps/src/main/java/org/akvo/flow/offlinemaps/Constants.java
offlinemaps/src/main/java/org/akvo/flow/offlinemaps/presentation/MapBoxMapPresenter.java
offlinemaps/src/main/java/org/akvo/flow/offlinemaps/presentation/OfflineMapsFloatingActionButton.java
offlinemaps/src/main/java/org/akvo/flow/offlinemaps/presentation/download/OfflineMapDownloadActivity.java

NA
part2 of abstracting maps. All the mapbox related code is moved to offlinemaps module
final solution https://github.com/akvo/akvo-flow-mobile/pull/1425
this part will probably not compile as some classes are missing
NA

[#1425] part2 of abstracting maps away from the presentation layer

---

offlinemaps/src/main/java/org/akvo/flow/offlinemaps/presentation/MapBoxMapItemListViewImpl.java

NA
When switching surveys in offline mode, the mabox map made the app crash. Added a Null check. Due to the crash the window displaying the previous datapoint also did not get dismissed
NA

[#1445] fixed crash when offline

---

app/src/main/AndroidManifest.xml

Crash when trying to fill a goeshape question with and and Android 9.0 device
Applied the fix suggested https://stackoverflow.com/questions/50782806/android-google-maps-java-lang-noclassdeffounderror-failed-resolution-of-lorg-a
Crash no longer happens
NA

[#1458] fix geoshape activity crash

---

app/src/main/java/org/akvo/flow/presentation/geoshape/LengthCounter.java
app/src/main/java/org/akvo/flow/presentation/geoshape/create/CoordinatesMapper.java
app/src/main/java/org/akvo/flow/presentation/geoshape/create/DrawMode.java
app/src/main/res/menu/create_geoshape_activity_bottom.xml
offlinemaps/src/main/AndroidManifest.xml
offlinemaps/src/main/java/org/akvo/flow/offlinemaps/presentation/geoshapes/GeoShapeConstants.java
offlinemaps/src/main/java/org/akvo/flow/offlinemaps/presentation/geoshapes/GeoShapesClickListener.java
offlinemaps/src/main/java/org/akvo/flow/offlinemaps/presentation/geoshapes/GeoShapesMapPresenter.java
offlinemaps/src/main/java/org/akvo/flow/offlinemaps/presentation/geoshapes/GeoShapesMapView.java
uicomponents/src/main/res/values/strings.xml

Geoshapes use google maps, offline areas cannot be used.
Part 1 of Creating geoshapes using the mapbox library
Added base classes for the app module (utility classes)
Added one bottom menu item
Added mabox and geoshape related classes
final solution https://github.com/akvo/akvo-flow-mobile/pull/1471
NA

[#1447] initial geoshape and mapbox related classes

---

app/src/main/AndroidManifest.xml

There is a crash on Android 9 or 10 devices when we try to start a foreground service (the one that deletes files after publishing them
Add the missing permission to manifest
NA

[#1489] added missing permission

---

.gitignore
app/src/main/resources/sentry.properties

All crashes and exceptions are sent to sentry
sample to 0.75 so only about 75% will be sent
NA

[#1545] add sampling to 0.75 for sentry

---

app/src/androidTest/java/org/akvo/flow/activity/form/data/SurveyInstaller.java
app/src/androidTest/java/org/akvo/flow/activity/form/formsview/RepeatedGroupFormViewTest.kt
app/src/androidTest/res/raw/repeated_one_group_form_2questions.xml
app/src/main/java/org/akvo/flow/ui/view/QuestionGroupTab.java

If a repeated question was left unanswered and you left the datapoint and opened the saved datapoint again, the first repetition was fine but after the second one, the responses were filled on the empty questions using the ones for the first repetition.
* repeated group responses will no longer be duplicated on empty questions
* added comments to explain and a TODO
NA

[#1555] added a "fix" for the question group bug

---

app/src/main/java/org/akvo/flow/broadcast/UpdateReceiver.java
app/src/main/java/org/akvo/flow/presentation/settings/PreferenceActivity.java
app/src/main/java/org/akvo/flow/service/DataFixWorker.java
app/src/main/java/org/akvo/flow/service/DataPointUploadWorker.java
app/src/main/java/org/akvo/flow/util/NotificationHelper.java
uicomponents/src/main/res/values/strings.xml

When for some reason a datapoint's zip file was not submitted, because of a crash for example, that tdatapoint was stuck in "SUBMIT REQUESTED" state and would only be recreated if the app was updated.
When pressing sync in settings, also add the logic to recreate all datapoints that were not created properly before attempting to send it.
NA

[#1572] added way to fix a stuck datapoint by pressing sync in settings

---

data/src/main/java/org/akvo/flow/data/datasource/DatabaseDataSource.java
data/src/main/java/org/akvo/flow/data/repository/DataPointDataRepository.kt
data/src/test/java/org/akvo/flow/data/repository/DataPointDataRepositoryTest.kt
database/src/main/java/org/akvo/flow/database/britedb/BriteSurveyDbAdapter.java

When datapoints are downloaded, those that are not in the list get deleted
Stop deleting (unassigned) datapoints
No datapoint will be deleted for now
NA

[#1590] stop deleting datapoints

---

app/src/main/java/org/akvo/flow/activity/SurveyActivity.java
data/src/main/java/org/akvo/flow/data/net/RestApi.java
data/src/test/java/org/akvo/flow/data/repository/DataPointDataRepositoryTest.kt

When first downloading the app, the forms are not immediately downloaded and user has to manually restart the app
Fix the issue where the phone data was not properly updated once permissions were granted
NA

[#1611] fix issue with forms not being downloaded

---

app/src/main/java/org/akvo/flow/presentation/datapoints/DataPointSyncSnackBarManager.java
app/src/main/java/org/akvo/flow/presentation/datapoints/list/DataPointsListFragment.java
app/src/main/java/org/akvo/flow/presentation/datapoints/list/DataPointsListPresenter.java
app/src/main/java/org/akvo/flow/presentation/datapoints/list/DataPointsListView.java
app/src/main/java/org/akvo/flow/presentation/datapoints/map/DataPointsMapFragment.java
app/src/main/java/org/akvo/flow/presentation/datapoints/map/DataPointsMapPresenter.java
app/src/main/java/org/akvo/flow/presentation/datapoints/map/DataPointsMapView.java
data/src/main/java/org/akvo/flow/data/datasource/DatabaseDataSource.java
data/src/main/java/org/akvo/flow/data/repository/DataPointDataRepository.kt
data/src/test/java/org/akvo/flow/data/repository/DataPointDataRepositoryTest.kt
database/src/main/java/org/akvo/flow/database/britedb/BriteSurveyDbAdapter.java
domain/src/main/java/org/akvo/flow/domain/entity/DownloadResult.java

The message is misleading, we say x datapoints downloaded even if there is nothing new but the same old datapoints
* display the number of new downloaded datapoints
* rename some methods related to datapoint download
* some "formatting" fixes
NA

[#1599] improve datapoint download message

---

app/src/main/java/org/akvo/flow/ui/view/SubmitTab.java

NA
Unexpected divider in Submit Tab footer needs to be removed.

[#1620] remove divider from list footer and header

---

app/src/main/java/org/akvo/flow/ui/view/GeoshapeQuestionView.java
uicomponents/src/main/res/values/strings.xml

The button text was inconsistent
Update the button text once a shape has already been captured

[#1637] updated text for geoshape button

---

app/src/main/java/org/akvo/flow/presentation/geoshape/create/CreateGeoShapeActivity.java
app/src/main/java/org/akvo/flow/presentation/geoshape/create/CreateGeoShapePresenter.java

NA
Now when user pressed the device back button or the top toolbar button,
the shape will be saved and added as result to the form
NA

[#1199] adds "auto-save" to geoshapes

---

app/src/main/java/org/akvo/flow/ui/view/geolocation/GeoInputContainer.java
app/src/main/java/org/akvo/flow/ui/view/geolocation/GeoQuestionView.java

The accuracy tip shown even if we have no location data yet
do not display the accuracy tip when no location data yet
+ removed empty method
NA

[#1680] do not display the accuracy tip when no location data yet

---

app/src/main/java/org/akvo/flow/event/TimedLocationListener.java
app/src/main/java/org/akvo/flow/ui/view/geolocation/GeoQuestionView.java

When user requested location capture but location provider was disabled
the snackbar was not shown and the "loading" ui was displayed incorrectly
Fixed: only once the location is being listened to, we display the loading ui

[#1722] Fixed location issue

---

app/proguard-files/proguard-rules.pro
app/src/main/java/org/akvo/flow/activity/SurveyActivity.java
app/src/main/java/org/akvo/flow/presentation/navigation/FlowNavigationView.kt
app/src/main/java/org/akvo/flow/presentation/survey/CustomDrawerArrowDrawable.kt
app/src/main/res/drawable/ic_new_forms_icon.xml

User does not know there are newly downloaded forms without opening the navigation drawer
display a dot on top of the drawer toggle icon when there are new forms
NA

[#1754] drawer new dot display

---

app/src/main/java/org/akvo/flow/presentation/survey/CustomDrawerArrowDrawable.kt

There was a crash on Android 4 devices because a method was added later

[#1754] fix crash on Android 4 devices for a method which did not exist
